"""Task 2b (DOUBTS D7) — FULL significance table with multiple-comparison control.

significance.py audited the headline cells. A reviewer will want the complete
block x type contingency analysis with a correction for multiple testing. This
computes, for EVERY (article-type, block) cell, the type-vs-rest 2x2 test
(chi-square, or Fisher when any expected cell < 5), a Wilson 95% CI on the
within-type rate, and then applies the Benjamini-Hochberg FDR procedure (q=0.05)
across all cells. Output: SIGNIFICANCE_FULL.md.

Run:  python significance_full.py
"""
import os
from collections import Counter, defaultdict

from _common import iter_mw, detect_blocks, classify_type, BLOCK_ORDER, TYPE_ORDER
from significance import wilson, pval_2x2

HERE = os.path.dirname(os.path.abspath(__file__))
Q = 0.05


def benjamini_hochberg(pvals, q=0.05):
    """Return a set of indices rejected (significant) under BH FDR at level q."""
    m = len(pvals)
    order = sorted(range(m), key=lambda i: pvals[i])
    thresh_k = -1
    for rank, i in enumerate(order, start=1):
        if pvals[i] <= (rank / m) * q:
            thresh_k = rank
    if thresh_k < 0:
        return set()
    return set(order[:thresh_k])


def main():
    print('Loading + classifying...')
    type_count = Counter()
    block_total = Counter()
    matrix = defaultdict(Counter)
    n = 0
    for r in iter_mw():
        blocks = detect_blocks(r['body'])
        types = classify_type(r['body'], r['k2'], r['ecode'])
        n += 1
        for b in blocks:
            block_total[b] += 1
        for t in types:
            type_count[t] += 1
            for b in blocks:
                matrix[t][b] += 1
    print(f'  {n:,} records')

    present = [t for t in TYPE_ORDER if type_count[t] > 0]
    cells = []  # (t, b, a, row_t, pct, lo, hi, base, p, test)
    for t in present:
        row_t = type_count[t]
        for b in BLOCK_ORDER:
            a = matrix[t][b]
            c = block_total[b] - a
            d = (n - row_t) - c
            p, test = pval_2x2(a, row_t - a, c, d)
            lo, hi = wilson(a, row_t)
            base = 100 * c / (c + d) if (c + d) else 0
            cells.append((t, b, a, row_t, 100*a/row_t, 100*lo, 100*hi, base, p, test))

    pvals = [c[8] for c in cells]
    rejected = benjamini_hochberg(pvals, Q)
    n_sig = len(rejected)

    lines = []
    def out(s=''):
        lines.append(s)
    out(f'Full block x type significance — {len(cells)} cells '
        f'({len(present)} types x {len(BLOCK_ORDER)} blocks)')
    out(f'Tests: chi-square (Yates) or Fisher exact (expected<5). '
        f'Multiple comparisons: Benjamini-Hochberg FDR at q={Q}.')
    out(f'Significant after FDR: {n_sig} / {len(cells)} cells.')
    out(f'Raw p<0.05 (uncorrected): {sum(1 for p in pvals if p < 0.05)} cells.')
    out('')
    out(f'{"type":<18}{"blk":<5}{"k":>8}{"N":>8}{"pct":>7}{"  95% CI":>15}'
        f'{"base":>7}{"p":>11}{"test":>8}{"  FDR":>6}')
    for idx, (t, b, a, row_t, pct, lo, hi, base, p, test) in enumerate(cells):
        sig = '*' if idx in rejected else ''
        out(f'{t:<18}{b:<5}{a:>8,}{row_t:>8,}{pct:>6.1f}%'
            f'{f"[{lo:.1f},{hi:.1f}]":>15}{base:>6.1f}%{p:>11.2e}{test:>8}{sig:>6}')

    report = os.path.join(HERE, 'SIGNIFICANCE_FULL.md')
    with open(report, 'w', encoding='utf-8') as f:
        f.write('# Full block x type significance table, FDR-corrected (DOUBTS D7)\n\n')
        f.write('Generated by `significance_full.py`. Every (article-type, block) cell tested '
                'type-vs-rest (chi-square / Fisher), Wilson 95% CIs, Benjamini-Hochberg FDR at '
                'q=0.05. A `*` in the FDR column = significant after correction.\n\n')
        f.write('```\n' + '\n'.join(lines).strip() + '\n```\n')
    print('\n'.join(lines[:6]))
    print(f'\n  wrote {report}')


if __name__ == '__main__':
    main()
