cp 'mwcolorpages/MW-main (coloured) 1.pdf' pdfpages/mw0001-a.pdf
cp 'mwcolorpages/MW-main (coloured) 10.pdf' pdfpages/mw0010-ajanayonija.pdf
cp 'mwcolorpages/MW-main (coloured) 100.pdf' pdfpages/mw0100-avadhIr.pdf
cp 'mwcolorpages/MW-main (coloured) 1000.pdf' pdfpages/mw1000-viSNubhagavatapurANa.pdf
cp 'mwcolorpages/MW-main (coloured) 1001.pdf' pdfpages/mw1001-visArin.pdf
cp 'mwcolorpages/MW-main (coloured) 1002.pdf' pdfpages/mw1002-vispaSTI.pdf
cp 'mwcolorpages/MW-main (coloured) 1003.pdf' pdfpages/mw1003-vihata.pdf
cp 'mwcolorpages/MW-main (coloured) 1004.pdf' pdfpages/mw1004-vihvalita.pdf
cp 'mwcolorpages/MW-main (coloured) 1005.pdf' pdfpages/mw1005-vIDu.pdf
cp 'mwcolorpages/MW-main (coloured) 1006.pdf' pdfpages/mw1006-virabhaTa.pdf
cp 'mwcolorpages/MW-main (coloured) 1007.pdf' pdfpages/mw1007-vIryAsattvavat.pdf
cp 'mwcolorpages/MW-main (coloured) 1008.pdf' pdfpages/mw1008-vRthAprajA.pdf
cp 'mwcolorpages/MW-main (coloured) 1009.pdf' pdfpages/mw1009-varja.pdf
cp 'mwcolorpages/MW-main (coloured) 101.pdf' pdfpages/mw0101-avapAtana.pdf
cp 'mwcolorpages/MW-main (coloured) 1010.pdf' pdfpages/mw1010-vRttervAru.pdf
cp 'mwcolorpages/MW-main (coloured) 1011.pdf' pdfpages/mw1011-vRddhayogazataka.pdf
cp 'mwcolorpages/MW-main (coloured) 1012.pdf' pdfpages/mw1012-vRSakarNikA.pdf
cp 'mwcolorpages/MW-main (coloured) 1013.pdf' pdfpages/mw1013-vRSaya.pdf
cp 'mwcolorpages/MW-main (coloured) 1014.pdf' pdfpages/mw1014-veGkaTa.pdf
cp 'mwcolorpages/MW-main (coloured) 1015.pdf' pdfpages/mw1015-vetAlapura.pdf
cp 'mwcolorpages/MW-main (coloured) 1016.pdf' pdfpages/mw1016-vedabIja.pdf
cp 'mwcolorpages/MW-main (coloured) 1017.pdf' pdfpages/mw1017-vedAGgazAstra.pdf
cp 'mwcolorpages/MW-main (coloured) 1018.pdf' pdfpages/mw1018-vedyupoSaNa.pdf
cp 'mwcolorpages/MW-main (coloured) 1019.pdf' pdfpages/mw1019-vellitAgra.pdf
cp 'mwcolorpages/MW-main (coloured) 102.pdf' pdfpages/mw0102-avamAnanIya.pdf
cp 'mwcolorpages/MW-main (coloured) 1020.pdf' pdfpages/mw1020-vaiMzatika.pdf
cp 'mwcolorpages/MW-main (coloured) 1021.pdf' pdfpages/mw1021-vaicittya.pdf
cp 'mwcolorpages/MW-main (coloured) 1022.pdf' pdfpages/mw1022-vaitAlI.pdf
cp 'mwcolorpages/MW-main (coloured) 1023.pdf' pdfpages/mw1023-vaidyAni.pdf
cp 'mwcolorpages/MW-main (coloured) 1024.pdf' pdfpages/mw1024-vaibhAjyavAdin.pdf
cp 'mwcolorpages/MW-main (coloured) 1025.pdf' pdfpages/mw1025-vairakRt.pdf
cp 'mwcolorpages/MW-main (coloured) 1026.pdf' pdfpages/mw1026-vaivarNika.pdf
cp 'mwcolorpages/MW-main (coloured) 1027.pdf' pdfpages/mw1027-vaizvadeva.pdf
cp 'mwcolorpages/MW-main (coloured) 1028.pdf' pdfpages/mw1028-vaisarjanIya.pdf
cp 'mwcolorpages/MW-main (coloured) 1029.pdf' pdfpages/mw1029-vyudaka.pdf
cp 'mwcolorpages/MW-main (coloured) 103.pdf' pdfpages/mw0103-avarodhika.pdf
cp 'mwcolorpages/MW-main (coloured) 1030.pdf' pdfpages/mw1030-vyatikaratikRta.pdf
cp 'mwcolorpages/MW-main (coloured) 1031.pdf' pdfpages/mw1031-vyatIhAra.pdf
cp 'mwcolorpages/MW-main (coloured) 1032.pdf' pdfpages/mw1032-vyapavRj.pdf
cp 'mwcolorpages/MW-main (coloured) 1033.pdf' pdfpages/mw1033-vyavakRR.pdf
cp 'mwcolorpages/MW-main (coloured) 1034.pdf' pdfpages/mw1034-vyavasthApakavasthApanIya.pdf
cp 'mwcolorpages/MW-main (coloured) 1035.pdf' pdfpages/mw1035-vyasana.pdf
cp 'mwcolorpages/MW-main (coloured) 1036.pdf' pdfpages/mw1036-vyAkRS.pdf
cp 'mwcolorpages/MW-main (coloured) 1037.pdf' pdfpages/mw1037-vyADiparibhASA.pdf
cp 'mwcolorpages/MW-main (coloured) 1038.pdf' pdfpages/mw1038-vyApAta.pdf
cp 'mwcolorpages/MW-main (coloured) 1039.pdf' pdfpages/mw1039-vyAvarN.pdf
cp 'mwcolorpages/MW-main (coloured) 104.pdf' pdfpages/mw0104-avalobhana.pdf
cp 'mwcolorpages/MW-main (coloured) 1040.pdf' pdfpages/mw1040-vyukS.pdf
cp 'mwcolorpages/MW-main (coloured) 1041.pdf' pdfpages/mw1041-vyuSita.pdf
cp 'mwcolorpages/MW-main (coloured) 1042.pdf' pdfpages/mw1042-vrAja.pdf
cp 'mwcolorpages/MW-main (coloured) 1043.pdf' pdfpages/mw1043-vratayitavya.pdf
cp 'mwcolorpages/MW-main (coloured) 1044.pdf' pdfpages/mw1044-zaMsa.pdf
cp 'mwcolorpages/MW-main (coloured) 1045.pdf' pdfpages/mw1045-zaktivega.pdf
cp 'mwcolorpages/MW-main (coloured) 1046.pdf' pdfpages/mw1046-zakArilipi.pdf
cp 'mwcolorpages/MW-main (coloured) 1047.pdf' pdfpages/mw1047-zakman.pdf
cp 'mwcolorpages/MW-main (coloured) 1048.pdf' pdfpages/mw1048-zaGkhamAlini.pdf
cp 'mwcolorpages/MW-main (coloured) 1049.pdf' pdfpages/mw1049-zatakrI.pdf
cp 'mwcolorpages/MW-main (coloured) 105.pdf' pdfpages/mw0105-avasAda.pdf
cp 'mwcolorpages/MW-main (coloured) 1050.pdf' pdfpages/mw1050-zatamaya.pdf
cp 'mwcolorpages/MW-main (coloured) 1051.pdf' pdfpages/mw1051-zatepaJcAzannyAya.pdf
cp 'mwcolorpages/MW-main (coloured) 1052.pdf' pdfpages/mw1052-zap.pdf
cp 'mwcolorpages/MW-main (coloured) 1053.pdf' pdfpages/mw1053-zabdabrahman.pdf
cp 'mwcolorpages/MW-main (coloured) 1054.pdf' pdfpages/mw1054-zamavyasanin.pdf
cp 'mwcolorpages/MW-main (coloured) 1055.pdf' pdfpages/mw1055-zaMkaravilAsa.pdf
cp 'mwcolorpages/MW-main (coloured) 1056.pdf' pdfpages/mw1056-zayanagRha.pdf
cp 'mwcolorpages/MW-main (coloured) 1057.pdf' pdfpages/mw1057-zaryahan.pdf
cp 'mwcolorpages/MW-main (coloured) 1058.pdf' pdfpages/mw1058-zarIranipAta.pdf
cp 'mwcolorpages/MW-main (coloured) 1059.pdf' pdfpages/mw1059-zalalita.pdf
cp 'mwcolorpages/MW-main (coloured) 106.pdf' pdfpages/mw0106-avatha.pdf
cp 'mwcolorpages/MW-main (coloured) 1060.pdf' pdfpages/mw1060-zaza.pdf
cp 'mwcolorpages/MW-main (coloured) 1061.pdf' pdfpages/mw1061-zastrakali.pdf
cp 'mwcolorpages/MW-main (coloured) 1062.pdf' pdfpages/mw1062-zAkaMdheya.pdf
cp 'mwcolorpages/MW-main (coloured) 1063.pdf' pdfpages/mw1063-zAkhAmlA.pdf
cp 'mwcolorpages/MW-main (coloured) 1064.pdf' pdfpages/mw1064-zAtita.pdf
cp 'mwcolorpages/MW-main (coloured) 1065.pdf' pdfpages/mw1065-zAntisarvasva.pdf
cp 'mwcolorpages/MW-main (coloured) 1066.pdf' pdfpages/mw1066-zAyitA.pdf
cp 'mwcolorpages/MW-main (coloured) 1067.pdf' pdfpages/mw1067-zArGgaSTA.pdf
cp 'mwcolorpages/MW-main (coloured) 1068.pdf' pdfpages/mw1068-zAlAluka.pdf
cp 'mwcolorpages/MW-main (coloured) 1069.pdf' pdfpages/mw1069-zAsanadUSaka.pdf
cp 'mwcolorpages/MW-main (coloured) 107.pdf' pdfpages/mw0107-avAcinazIrSan.pdf
cp 'mwcolorpages/MW-main (coloured) 1070.pdf' pdfpages/mw1070-zikyita.pdf
cp 'mwcolorpages/MW-main (coloured) 1071.pdf' pdfpages/mw1071-zikhi.pdf
cp 'mwcolorpages/MW-main (coloured) 1072.pdf' pdfpages/mw1072-zineyu.pdf
cp 'mwcolorpages/MW-main (coloured) 1073.pdf' pdfpages/mw1073-ziromukha.pdf
cp 'mwcolorpages/MW-main (coloured) 1074.pdf' pdfpages/mw1074-zilpasarvasvasaMgraha.pdf
cp 'mwcolorpages/MW-main (coloured) 1075.pdf' pdfpages/mw1075-zivadhanurveda.pdf
cp 'mwcolorpages/MW-main (coloured) 1076.pdf' pdfpages/mw1076-zivApriyA.pdf
cp 'mwcolorpages/MW-main (coloured) 1077.pdf' pdfpages/mw1077-ziSTAcIrNa.pdf
cp 'mwcolorpages/MW-main (coloured) 1078.pdf' pdfpages/mw1078-zItameha.pdf
cp 'mwcolorpages/MW-main (coloured) 1079.pdf' pdfpages/mw1079-zIrSAmaya.pdf
cp 'mwcolorpages/MW-main (coloured) 108.pdf' pdfpages/mw0108-avigAna.pdf
cp 'mwcolorpages/MW-main (coloured) 1080.pdf' pdfpages/mw1080-zukIbhU.pdf
cp 'mwcolorpages/MW-main (coloured) 1081.pdf' pdfpages/mw1081-zuklIkR.pdf
cp 'mwcolorpages/MW-main (coloured) 1082.pdf' pdfpages/mw1082-zudh.pdf
cp 'mwcolorpages/MW-main (coloured) 1083.pdf' pdfpages/mw1083-zunaHzepazepha.pdf
cp 'mwcolorpages/MW-main (coloured) 1084.pdf' pdfpages/mw1084-zubhetara.pdf
cp 'mwcolorpages/MW-main (coloured) 1085.pdf' pdfpages/mw1085-zuSkavraNa.pdf
cp 'mwcolorpages/MW-main (coloured) 1086.pdf' pdfpages/mw1086-zUdravarga.pdf
cp 'mwcolorpages/MW-main (coloured) 1087.pdf' pdfpages/mw1087-zUlAkR.pdf
cp 'mwcolorpages/MW-main (coloured) 1088.pdf' pdfpages/mw1088-zRGgAraka.pdf
cp 'mwcolorpages/MW-main (coloured) 1089.pdf' pdfpages/mw1089-zeSakamalAkara.pdf
cp 'mwcolorpages/MW-main (coloured) 109.pdf' pdfpages/mw0109-avina.pdf
cp 'mwcolorpages/MW-main (coloured) 1090.pdf' pdfpages/mw1090-zailapatha.pdf
cp 'mwcolorpages/MW-main (coloured) 1091.pdf' pdfpages/mw1091-zaiSyopAdhyAyikA.pdf
cp 'mwcolorpages/MW-main (coloured) 1092.pdf' pdfpages/mw1092-zodhayitavya.pdf
cp 'mwcolorpages/MW-main (coloured) 1093.pdf' pdfpages/mw1093-zauNDarya.pdf
cp 'mwcolorpages/MW-main (coloured) 1094.pdf' pdfpages/mw1094-zcut.pdf
cp 'mwcolorpages/MW-main (coloured) 1095.pdf' pdfpages/mw1095-zyAmAdevI.pdf
cp 'mwcolorpages/MW-main (coloured) 1096.pdf' pdfpages/mw1096-zraddhApana.pdf
cp 'mwcolorpages/MW-main (coloured) 1097.pdf' pdfpages/mw1097-zravas.pdf
cp 'mwcolorpages/MW-main (coloured) 1098.pdf' pdfpages/mw1098-zrAddhapaddhati.pdf
cp 'mwcolorpages/MW-main (coloured) 1099.pdf' pdfpages/mw1099-zrIkAra.pdf
cp 'mwcolorpages/MW-main (coloured) 11.pdf' pdfpages/mw0011-aJcati.pdf
cp 'mwcolorpages/MW-main (coloured) 110.pdf' pdfpages/mw0110-avilA.pdf
cp 'mwcolorpages/MW-main (coloured) 1100.pdf' pdfpages/mw1100-zrIraGga.pdf
cp 'mwcolorpages/MW-main (coloured) 1101.pdf' pdfpages/mw1101-zuzruvas.pdf
cp 'mwcolorpages/MW-main (coloured) 1102.pdf' pdfpages/mw1102-zrutimUla.pdf
cp 'mwcolorpages/MW-main (coloured) 1103.pdf' pdfpages/mw1103-zroNikapAla.pdf
cp 'mwcolorpages/MW-main (coloured) 1104.pdf' pdfpages/mw1104-zlAghA.pdf
cp 'mwcolorpages/MW-main (coloured) 1105.pdf' pdfpages/mw1105-zvaTha.pdf
cp 'mwcolorpages/MW-main (coloured) 1106.pdf' pdfpages/mw1106-zvasIvat.pdf
cp 'mwcolorpages/MW-main (coloured) 1107.pdf' pdfpages/mw1107-zvetanAman.pdf
cp 'mwcolorpages/MW-main (coloured) 1108.pdf' pdfpages/mw1108-SaNDakApAlika.pdf
cp 'mwcolorpages/MW-main (coloured) 1109.pdf' pdfpages/mw1109-SaDaGginI.pdf
cp 'mwcolorpages/MW-main (coloured) 111.pdf' pdfpages/mw0111-avRdha.pdf
cp 'mwcolorpages/MW-main (coloured) 1110.pdf' pdfpages/mw1110-SaSTisahasra.pdf
cp 'mwcolorpages/MW-main (coloured) 1111.pdf' pdfpages/mw1111-SANDaza.pdf
cp 'mwcolorpages/MW-main (coloured) 1112.pdf' pdfpages/mw1112-saMyataka.pdf
cp 'mwcolorpages/MW-main (coloured) 1113.pdf' pdfpages/mw1113-saMrambha.pdf
cp 'mwcolorpages/MW-main (coloured) 1114.pdf' pdfpages/mw1114-saMvac.pdf
cp 'mwcolorpages/MW-main (coloured) 1115.pdf' pdfpages/mw1115-saMvAhaka.pdf
cp 'mwcolorpages/MW-main (coloured) 1116.pdf' pdfpages/mw1116-saMveza.pdf
cp 'mwcolorpages/MW-main (coloured) 1117.pdf' pdfpages/mw1117-saMve.pdf
cp 'mwcolorpages/MW-main (coloured) 1118.pdf' pdfpages/mw1118-saMzodhana.pdf
cp 'mwcolorpages/MW-main (coloured) 1119.pdf' pdfpages/mw1119-saMsakti.pdf
cp 'mwcolorpages/MW-main (coloured) 112.pdf' pdfpages/mw0112-avyavalambin.pdf
cp 'mwcolorpages/MW-main (coloured) 1120.pdf' pdfpages/mw1120-saMsargaka.pdf
cp 'mwcolorpages/MW-main (coloured) 1121.pdf' pdfpages/mw1121-saMskRtatra.pdf
cp 'mwcolorpages/MW-main (coloured) 1122.pdf' pdfpages/mw1122-saMsthitika.pdf
cp 'mwcolorpages/MW-main (coloured) 1123.pdf' pdfpages/mw1123-saMhita.pdf
cp 'mwcolorpages/MW-main (coloured) 1124.pdf' pdfpages/mw1124-sakalatra.pdf
cp 'mwcolorpages/MW-main (coloured) 1125.pdf' pdfpages/mw1125-sakSama.pdf
cp 'mwcolorpages/MW-main (coloured) 1126.pdf' pdfpages/mw1126-saMkuJcita.pdf
cp 'mwcolorpages/MW-main (coloured) 1127.pdf' pdfpages/mw1127-saMketagRhaka.pdf
cp 'mwcolorpages/MW-main (coloured) 1128.pdf' pdfpages/mw1128-saMkSepaka.pdf
cp 'mwcolorpages/MW-main (coloured) 1129.pdf' pdfpages/mw1129-saMjughukSA.pdf
cp 'mwcolorpages/MW-main (coloured) 113.pdf' pdfpages/mw0113-azanika.pdf
cp 'mwcolorpages/MW-main (coloured) 1130.pdf' pdfpages/mw1130-saMghabhadra.pdf
cp 'mwcolorpages/MW-main (coloured) 1131.pdf' pdfpages/mw1131-sacitra.pdf
cp 'mwcolorpages/MW-main (coloured) 1132.pdf' pdfpages/mw1132-saMcAri.pdf
cp 'mwcolorpages/MW-main (coloured) 1133.pdf' pdfpages/mw1133-saGgaTa.pdf
cp 'mwcolorpages/MW-main (coloured) 1134.pdf' pdfpages/mw1134-saMjvara.pdf
cp 'mwcolorpages/MW-main (coloured) 1135.pdf' pdfpages/mw1135-satsaMgati.pdf
cp 'mwcolorpages/MW-main (coloured) 1136.pdf' pdfpages/mw1136-satyacUDAmaNi.pdf
cp 'mwcolorpages/MW-main (coloured) 1137.pdf' pdfpages/mw1137-satyApariNaya.pdf
cp 'mwcolorpages/MW-main (coloured) 1138.pdf' pdfpages/mw1138-satApa.pdf
cp 'mwcolorpages/MW-main (coloured) 1139.pdf' pdfpages/mw1139-sadmanivAsin.pdf
cp 'mwcolorpages/MW-main (coloured) 114.pdf' pdfpages/mw0114-azokataru.pdf
cp 'mwcolorpages/MW-main (coloured) 1140.pdf' pdfpages/mw1140-sadAtana.pdf
cp 'mwcolorpages/MW-main (coloured) 1141.pdf' pdfpages/mw1141-sanitR.pdf
cp 'mwcolorpages/MW-main (coloured) 1142.pdf' pdfpages/mw1142-saMtatatika.pdf
cp 'mwcolorpages/MW-main (coloured) 1143.pdf' pdfpages/mw1143-saMtrAsita.pdf
cp 'mwcolorpages/MW-main (coloured) 1144.pdf' pdfpages/mw1144-saMduSTa.pdf
cp 'mwcolorpages/MW-main (coloured) 1145.pdf' pdfpages/mw1145-saMdhicamasa.pdf
cp 'mwcolorpages/MW-main (coloured) 1146.pdf' pdfpages/mw1146-saMnakha.pdf
cp 'mwcolorpages/MW-main (coloured) 1147.pdf' pdfpages/mw1147-saMnipAtaka.pdf
cp 'mwcolorpages/MW-main (coloured) 1148.pdf' pdfpages/mw1148-saMnyas.pdf
cp 'mwcolorpages/MW-main (coloured) 1149.pdf' pdfpages/mw1149-saprazrayam.pdf
cp 'mwcolorpages/MW-main (coloured) 115.pdf' pdfpages/mw0115-azvakarNaka.pdf
cp 'mwcolorpages/MW-main (coloured) 1150.pdf' pdfpages/mw1150-saptabhauma.pdf
cp 'mwcolorpages/MW-main (coloured) 1151.pdf' pdfpages/mw1151-sapratipAdana.pdf
cp 'mwcolorpages/MW-main (coloured) 1152.pdf' pdfpages/mw1152-sam.pdf
cp 'mwcolorpages/MW-main (coloured) 1153.pdf' pdfpages/mw1153-samazarkara.pdf
cp 'mwcolorpages/MW-main (coloured) 1154.pdf' pdfpages/mw1154-samaNTha.pdf
cp 'mwcolorpages/MW-main (coloured) 1155.pdf' pdfpages/mw1155-samanubandha.pdf
cp 'mwcolorpages/MW-main (coloured) 1156.pdf' pdfpages/mw1156-samabhinand.pdf
cp 'mwcolorpages/MW-main (coloured) 1157.pdf' pdfpages/mw1157-samartharthaka.pdf
cp 'mwcolorpages/MW-main (coloured) 1158.pdf' pdfpages/mw1158-samavAyavAyana.pdf
cp 'mwcolorpages/MW-main (coloured) 1159.pdf' pdfpages/mw1159-samAkhyAkhyAna.pdf
cp 'mwcolorpages/MW-main (coloured) 116.pdf' pdfpages/mw0116-azvatthAman.pdf
cp 'mwcolorpages/MW-main (coloured) 1160.pdf' pdfpages/mw1160-samAdhita.pdf
cp 'mwcolorpages/MW-main (coloured) 1161.pdf' pdfpages/mw1161-samAnayana.pdf
cp 'mwcolorpages/MW-main (coloured) 1162.pdf' pdfpages/mw1162-samArudh.pdf
cp 'mwcolorpages/MW-main (coloured) 1163.pdf' pdfpages/mw1163-samAvyadh.pdf
cp 'mwcolorpages/MW-main (coloured) 1164.pdf' pdfpages/mw1164-sami.pdf
cp 'mwcolorpages/MW-main (coloured) 1165.pdf' pdfpages/mw1165-samIkSaNa.pdf
cp 'mwcolorpages/MW-main (coloured) 1166.pdf' pdfpages/mw1166-samutkRt.pdf
cp 'mwcolorpages/MW-main (coloured) 1167.pdf' pdfpages/mw1167-samudragamana.pdf
cp 'mwcolorpages/MW-main (coloured) 1168.pdf' pdfpages/mw1168-samuddidhIrSu.pdf
cp 'mwcolorpages/MW-main (coloured) 1169.pdf' pdfpages/mw1169-samunmUlana.pdf
cp 'mwcolorpages/MW-main (coloured) 117.pdf' pdfpages/mw0117-aSTa.pdf
cp 'mwcolorpages/MW-main (coloured) 1170.pdf' pdfpages/mw1170-samupAghrA.pdf
cp 'mwcolorpages/MW-main (coloured) 1171.pdf' pdfpages/mw1171-samaraNa.pdf
cp 'mwcolorpages/MW-main (coloured) 1172.pdf' pdfpages/mw1172-sampac.pdf
cp 'mwcolorpages/MW-main (coloured) 1173.pdf' pdfpages/mw1173-sampIti.pdf
cp 'mwcolorpages/MW-main (coloured) 1174.pdf' pdfpages/mw1174-sampracakS.pdf
cp 'mwcolorpages/MW-main (coloured) 1175.pdf' pdfpages/mw1175-sampratyavekSaNatA.pdf
cp 'mwcolorpages/MW-main (coloured) 1176.pdf' pdfpages/mw1176-samprayukta.pdf
cp 'mwcolorpages/MW-main (coloured) 1177.pdf' pdfpages/mw1177-samprahA.pdf
cp 'mwcolorpages/MW-main (coloured) 1178.pdf' pdfpages/mw1178-sambandhu.pdf
cp 'mwcolorpages/MW-main (coloured) 1179.pdf' pdfpages/mw1179-sambhava.pdf
cp 'mwcolorpages/MW-main (coloured) 118.pdf' pdfpages/mw0118-asakta.pdf
cp 'mwcolorpages/MW-main (coloured) 1180.pdf' pdfpages/mw1180-sammadin.pdf
cp 'mwcolorpages/MW-main (coloured) 1181.pdf' pdfpages/mw1181-sammUDha.pdf
cp 'mwcolorpages/MW-main (coloured) 1182.pdf' pdfpages/mw1182-sayoni.pdf
cp 'mwcolorpages/MW-main (coloured) 1183.pdf' pdfpages/mw1183-sarita.pdf
cp 'mwcolorpages/MW-main (coloured) 1184.pdf' pdfpages/mw1184-sargakartR.pdf
cp 'mwcolorpages/MW-main (coloured) 1185.pdf' pdfpages/mw1185-sarvaMsaha.pdf
cp 'mwcolorpages/MW-main (coloured) 1186.pdf' pdfpages/mw1186-sarvadevata.pdf
cp 'mwcolorpages/MW-main (coloured) 1187.pdf' pdfpages/mw1187-sarvarAj.pdf
cp 'mwcolorpages/MW-main (coloured) 1188.pdf' pdfpages/mw1188-sarvasulabha.pdf
cp 'mwcolorpages/MW-main (coloured) 1189.pdf' pdfpages/mw1189-sarveSTada.pdf
cp 'mwcolorpages/MW-main (coloured) 119.pdf' pdfpages/mw0119-asaMnikarSa.pdf
cp 'mwcolorpages/MW-main (coloured) 1190.pdf' pdfpages/mw1190-salajjita.pdf
cp 'mwcolorpages/MW-main (coloured) 1191.pdf' pdfpages/mw1191-savidhIkR.pdf
cp 'mwcolorpages/MW-main (coloured) 1192.pdf' pdfpages/mw1192-sazeSa.pdf
cp 'mwcolorpages/MW-main (coloured) 1193.pdf' pdfpages/mw1193-sah.pdf
cp 'mwcolorpages/MW-main (coloured) 1194.pdf' pdfpages/mw1194-sahajagdhi.pdf
cp 'mwcolorpages/MW-main (coloured) 1195.pdf' pdfpages/mw1195-sahotthAyin.pdf
cp 'mwcolorpages/MW-main (coloured) 1196.pdf' pdfpages/mw1196-sahasraparvA.pdf
cp 'mwcolorpages/MW-main (coloured) 1197.pdf' pdfpages/mw1197-sAMyuga.pdf
cp 'mwcolorpages/MW-main (coloured) 1198.pdf' pdfpages/mw1198-sAkSAtpuruSottamavAkya.pdf
cp 'mwcolorpages/MW-main (coloured) 1199.pdf' pdfpages/mw1199-sAMkrandani.pdf
cp 'mwcolorpages/MW-main (coloured) 12.pdf' pdfpages/mw0012-aNDara.pdf
cp 'mwcolorpages/MW-main (coloured) 120.pdf' pdfpages/mw0120-asaru.pdf
cp 'mwcolorpages/MW-main (coloured) 1200.pdf' pdfpages/mw1200-sADa.pdf
cp 'mwcolorpages/MW-main (coloured) 1201.pdf' pdfpages/mw1201-sAdh.pdf
cp 'mwcolorpages/MW-main (coloured) 1202.pdf' pdfpages/mw1202-sAdhya.pdf
cp 'mwcolorpages/MW-main (coloured) 1203.pdf' pdfpages/mw1203-sAnuja.pdf
cp 'mwcolorpages/MW-main (coloured) 1204.pdf' pdfpages/mw1204-sAMnivezika.pdf
cp 'mwcolorpages/MW-main (coloured) 1205.pdf' pdfpages/mw1205-sAman.pdf
cp 'mwcolorpages/MW-main (coloured) 1206.pdf' pdfpages/mw1206-sAmAjika.pdf
cp 'mwcolorpages/MW-main (coloured) 1207.pdf' pdfpages/mw1207-sAmpratakAla.pdf
cp 'mwcolorpages/MW-main (coloured) 1208.pdf' pdfpages/mw1208-sAr.pdf
cp 'mwcolorpages/MW-main (coloured) 1209.pdf' pdfpages/mw1209-sArameyAgaNAdhipa.pdf
cp 'mwcolorpages/MW-main (coloured) 121.pdf' pdfpages/mw0121-asiddhida.pdf
cp 'mwcolorpages/MW-main (coloured) 1210.pdf' pdfpages/mw1210-sArdhaMvihArin.pdf
cp 'mwcolorpages/MW-main (coloured) 1211.pdf' pdfpages/mw1211-sAvaka.pdf
cp 'mwcolorpages/MW-main (coloured) 1212.pdf' pdfpages/mw1212-sAzrunayana.pdf
cp 'mwcolorpages/MW-main (coloured) 1213.pdf' pdfpages/mw1213-sita.pdf
cp 'mwcolorpages/MW-main (coloured) 1214.pdf' pdfpages/mw1214-sikatAtva.pdf
cp 'mwcolorpages/MW-main (coloured) 1215.pdf' pdfpages/mw1215-sitIkR.pdf
cp 'mwcolorpages/MW-main (coloured) 1216.pdf' pdfpages/mw1216-siddhArthaka.pdf
cp 'mwcolorpages/MW-main (coloured) 1217.pdf' pdfpages/mw1217-sidhra.pdf
cp 'mwcolorpages/MW-main (coloured) 1218.pdf' pdfpages/mw1218-silAJjAlA.pdf
cp 'mwcolorpages/MW-main (coloured) 1219.pdf' pdfpages/mw1219-sImantaya.pdf
cp 'mwcolorpages/MW-main (coloured) 122.pdf' pdfpages/mw0122-asoDha.pdf
cp 'mwcolorpages/MW-main (coloured) 1220.pdf' pdfpages/mw1220-suUti.pdf
cp 'mwcolorpages/MW-main (coloured) 1221.pdf' pdfpages/mw1221-sukhakara.pdf
cp 'mwcolorpages/MW-main (coloured) 1222.pdf' pdfpages/mw1222-sukhAvaha.pdf
cp 'mwcolorpages/MW-main (coloured) 1223.pdf' pdfpages/mw1223-sugraha.pdf
cp 'mwcolorpages/MW-main (coloured) 1224.pdf' pdfpages/mw1224-sutamAm.pdf
cp 'mwcolorpages/MW-main (coloured) 1225.pdf' pdfpages/mw1225-suduHzrava.pdf
cp 'mwcolorpages/MW-main (coloured) 1226.pdf' pdfpages/mw1226-sudhAdIdhiti.pdf
cp 'mwcolorpages/MW-main (coloured) 1227.pdf' pdfpages/mw1227-sunaphAyoga.pdf
cp 'mwcolorpages/MW-main (coloured) 1228.pdf' pdfpages/mw1228-supAkya.pdf
cp 'mwcolorpages/MW-main (coloured) 1229.pdf' pdfpages/mw1229-suprasannaka.pdf
cp 'mwcolorpages/MW-main (coloured) 123.pdf' pdfpages/mw0123-asthituNDa.pdf
cp 'mwcolorpages/MW-main (coloured) 1230.pdf' pdfpages/mw1230-subhASin.pdf
cp 'mwcolorpages/MW-main (coloured) 1231.pdf' pdfpages/mw1231-sumanoharaNa.pdf
cp 'mwcolorpages/MW-main (coloured) 1232.pdf' pdfpages/mw1232-suyavasu.pdf
cp 'mwcolorpages/MW-main (coloured) 1233.pdf' pdfpages/mw1233-sulomadhi.pdf
cp 'mwcolorpages/MW-main (coloured) 1234.pdf' pdfpages/mw1234-suvihvala.pdf
cp 'mwcolorpages/MW-main (coloured) 1235.pdf' pdfpages/mw1235-suravIthI.pdf
cp 'mwcolorpages/MW-main (coloured) 1236.pdf' pdfpages/mw1236-surAmada.pdf
cp 'mwcolorpages/MW-main (coloured) 1237.pdf' pdfpages/mw1237-suvarNya.pdf
cp 'mwcolorpages/MW-main (coloured) 1238.pdf' pdfpages/mw1238-suSeNikA.pdf
cp 'mwcolorpages/MW-main (coloured) 1239.pdf' pdfpages/mw1239-susIman.pdf
cp 'mwcolorpages/MW-main (coloured) 124.pdf' pdfpages/mw0124-asvaka.pdf
cp 'mwcolorpages/MW-main (coloured) 1240.pdf' pdfpages/mw1240-sU.pdf
cp 'mwcolorpages/MW-main (coloured) 1241.pdf' pdfpages/mw1241-sUkSmAtman.pdf
cp 'mwcolorpages/MW-main (coloured) 1242.pdf' pdfpages/mw1242-sUtrakAra.pdf
cp 'mwcolorpages/MW-main (coloured) 1243.pdf' pdfpages/mw1243-sUpavaJcana.pdf
cp 'mwcolorpages/MW-main (coloured) 1244.pdf' pdfpages/mw1244-sUryavaMzya.pdf
cp 'mwcolorpages/MW-main (coloured) 1245.pdf' pdfpages/mw1245-sRtajava.pdf
cp 'mwcolorpages/MW-main (coloured) 1246.pdf' pdfpages/mw1246-sIrNi.pdf
cp 'mwcolorpages/MW-main (coloured) 1247.pdf' pdfpages/mw1247-sel.pdf
cp 'mwcolorpages/MW-main (coloured) 1248.pdf' pdfpages/mw1248-sainAnIka.pdf
cp 'mwcolorpages/MW-main (coloured) 1249.pdf' pdfpages/mw1249-sodarasneha.pdf
cp 'mwcolorpages/MW-main (coloured) 125.pdf' pdfpages/mw0125-ahalyA.pdf
cp 'mwcolorpages/MW-main (coloured) 1250.pdf' pdfpages/mw1250-somagRhapati.pdf
cp 'mwcolorpages/MW-main (coloured) 1251.pdf' pdfpages/mw1251-somasaptahautraprayoga.pdf
cp 'mwcolorpages/MW-main (coloured) 1252.pdf' pdfpages/mw1252-saukumArya.pdf
cp 'mwcolorpages/MW-main (coloured) 1253.pdf' pdfpages/mw1253-saudhAra.pdf
cp 'mwcolorpages/MW-main (coloured) 1254.pdf' pdfpages/mw1254-saumI.pdf
cp 'mwcolorpages/MW-main (coloured) 1255.pdf' pdfpages/mw1255-saurata.pdf
cp 'mwcolorpages/MW-main (coloured) 1256.pdf' pdfpages/mw1256-sauSmiki.pdf
cp 'mwcolorpages/MW-main (coloured) 1257.pdf' pdfpages/mw1257-skabdha.pdf
cp 'mwcolorpages/MW-main (coloured) 1258.pdf' pdfpages/mw1258-stambakari.pdf
cp 'mwcolorpages/MW-main (coloured) 1259.pdf' pdfpages/mw1259-stIma.pdf
cp 'mwcolorpages/MW-main (coloured) 126.pdf' pdfpages/mw0126-aho.pdf
cp 'mwcolorpages/MW-main (coloured) 1260.pdf' pdfpages/mw1260-staubhika.pdf
cp 'mwcolorpages/MW-main (coloured) 1261.pdf' pdfpages/mw1261-strIdhana.pdf
cp 'mwcolorpages/MW-main (coloured) 1262.pdf' pdfpages/mw1262-sthalakanda.pdf
cp 'mwcolorpages/MW-main (coloured) 1263.pdf' pdfpages/mw1263-sthAtavya.pdf
cp 'mwcolorpages/MW-main (coloured) 1264.pdf' pdfpages/mw1264-sthAman.pdf
cp 'mwcolorpages/MW-main (coloured) 1265.pdf' pdfpages/mw1265-sthirapratiSThA.pdf
cp 'mwcolorpages/MW-main (coloured) 1266.pdf' pdfpages/mw1266-sthaurya.pdf
cp 'mwcolorpages/MW-main (coloured) 1267.pdf' pdfpages/mw1267-snAnabhU.pdf
cp 'mwcolorpages/MW-main (coloured) 1268.pdf' pdfpages/mw1268-snu.pdf
cp 'mwcolorpages/MW-main (coloured) 1269.pdf' pdfpages/mw1269-spariza.pdf
cp 'mwcolorpages/MW-main (coloured) 127.pdf' pdfpages/mw0127-AkAzakakSA.pdf
cp 'mwcolorpages/MW-main (coloured) 1270.pdf' pdfpages/mw1270-spharaNa.pdf
cp 'mwcolorpages/MW-main (coloured) 1271.pdf' pdfpages/mw1271-sphur.pdf
cp 'mwcolorpages/MW-main (coloured) 1272.pdf' pdfpages/mw1272-smara.pdf
cp 'mwcolorpages/MW-main (coloured) 1273.pdf' pdfpages/mw1273-smRtisaMhitA.pdf
cp 'mwcolorpages/MW-main (coloured) 1274.pdf' pdfpages/mw1274-srastAGga.pdf
cp 'mwcolorpages/MW-main (coloured) 1275.pdf' pdfpages/mw1275-sraughnIya.pdf
cp 'mwcolorpages/MW-main (coloured) 1276.pdf' pdfpages/mw1276-svadharman.pdf
cp 'mwcolorpages/MW-main (coloured) 1277.pdf' pdfpages/mw1277-svavIkSita.pdf
cp 'mwcolorpages/MW-main (coloured) 1278.pdf' pdfpages/mw1278-svokta.pdf
cp 'mwcolorpages/MW-main (coloured) 1279.pdf' pdfpages/mw1279-svI.pdf
cp 'mwcolorpages/MW-main (coloured) 128.pdf' pdfpages/mw0128-AkIrNatA.pdf
cp 'mwcolorpages/MW-main (coloured) 1280.pdf' pdfpages/mw1280-svAdurAti.pdf
cp 'mwcolorpages/MW-main (coloured) 1281.pdf' pdfpages/mw1281-svapakSa.pdf
cp 'mwcolorpages/MW-main (coloured) 1282.pdf' pdfpages/mw1282-svaz.pdf
cp 'mwcolorpages/MW-main (coloured) 1283.pdf' pdfpages/mw1283-svasA.pdf
cp 'mwcolorpages/MW-main (coloured) 1284.pdf' pdfpages/mw1284-svAbhU.pdf
cp 'mwcolorpages/MW-main (coloured) 1285.pdf' pdfpages/mw1285-sveda.pdf
cp 'mwcolorpages/MW-main (coloured) 1286.pdf' pdfpages/mw1286-svocita.pdf
cp 'mwcolorpages/MW-main (coloured) 1287.pdf' pdfpages/mw1287-haJji.pdf
cp 'mwcolorpages/MW-main (coloured) 1288.pdf' pdfpages/mw1288-hananIya.pdf
cp 'mwcolorpages/MW-main (coloured) 1289.pdf' pdfpages/mw1289-hayi.pdf
cp 'mwcolorpages/MW-main (coloured) 129.pdf' pdfpages/mw0129-Akhara.pdf
cp 'mwcolorpages/MW-main (coloured) 1290.pdf' pdfpages/mw1290-harikeza.pdf
cp 'mwcolorpages/MW-main (coloured) 1291.pdf' pdfpages/mw1291-harizmazAru.pdf
cp 'mwcolorpages/MW-main (coloured) 1292.pdf' pdfpages/mw1292-hariman.pdf
cp 'mwcolorpages/MW-main (coloured) 1293.pdf' pdfpages/mw1293-harSula.pdf
cp 'mwcolorpages/MW-main (coloured) 1294.pdf' pdfpages/mw1294-haviSmat.pdf
cp 'mwcolorpages/MW-main (coloured) 1295.pdf' pdfpages/mw1295-hastagrAhaka.pdf
cp 'mwcolorpages/MW-main (coloured) 1296.pdf' pdfpages/mw1296-hastIkR.pdf
cp 'mwcolorpages/MW-main (coloured) 1297.pdf' pdfpages/mw1297-hInita.pdf
cp 'mwcolorpages/MW-main (coloured) 1298.pdf' pdfpages/mw1298-hiMsrajantu.pdf
cp 'mwcolorpages/MW-main (coloured) 1299.pdf' pdfpages/mw1299-himakuhAya.pdf
cp 'mwcolorpages/MW-main (coloured) 13.pdf' pdfpages/mw0013-atirucira.pdf
cp 'mwcolorpages/MW-main (coloured) 130.pdf' pdfpages/mw0130-Agomuc.pdf
cp 'mwcolorpages/MW-main (coloured) 1300.pdf' pdfpages/mw1300-hiraNyagupta.pdf
cp 'mwcolorpages/MW-main (coloured) 1301.pdf' pdfpages/mw1301-hava.pdf
cp 'mwcolorpages/MW-main (coloured) 1302.pdf' pdfpages/mw1302-hUna.pdf
cp 'mwcolorpages/MW-main (coloured) 1303.pdf' pdfpages/mw1303-hRdayazaithilya.pdf
cp 'mwcolorpages/MW-main (coloured) 1304.pdf' pdfpages/mw1304-hetumAtratA.pdf
cp 'mwcolorpages/MW-main (coloured) 1305.pdf' pdfpages/mw1305-hemAGka.pdf
cp 'mwcolorpages/MW-main (coloured) 1306.pdf' pdfpages/mw1306-hoDiman.pdf
cp 'mwcolorpages/MW-main (coloured) 1307.pdf' pdfpages/mw1307-hradecakSus.pdf
cp 'mwcolorpages/MW-main (coloured) 1308.pdf' pdfpages/mw1308-hvala.pdf
cp 'mwcolorpages/MW-main (coloured) 1309.pdf' pdfpages/mw1309.pdf
cp 'mwcolorpages/MW-main (coloured) 131.pdf' pdfpages/mw0131-AghoSa.pdf
cp 'mwcolorpages/MW-main (coloured) 1310.pdf' pdfpages/mw1310.pdf
cp 'mwcolorpages/MW-main (coloured) 1311.pdf' pdfpages/mw1311.pdf
cp 'mwcolorpages/MW-main (coloured) 1312.pdf' pdfpages/mw1312.pdf
cp 'mwcolorpages/MW-main (coloured) 1313.pdf' pdfpages/mw1313.pdf
cp 'mwcolorpages/MW-main (coloured) 1314.pdf' pdfpages/mw1314.pdf
cp 'mwcolorpages/MW-main (coloured) 1315.pdf' pdfpages/mw1315.pdf
cp 'mwcolorpages/MW-main (coloured) 1316.pdf' pdfpages/mw1316.pdf
cp 'mwcolorpages/MW-main (coloured) 1317.pdf' pdfpages/mw1317.pdf
cp 'mwcolorpages/MW-main (coloured) 1318.pdf' pdfpages/mw1318.pdf
cp 'mwcolorpages/MW-main (coloured) 1319.pdf' pdfpages/mw1319.pdf
cp 'mwcolorpages/MW-main (coloured) 132.pdf' pdfpages/mw0132-AcAryAnI.pdf
cp 'mwcolorpages/MW-main (coloured) 1320.pdf' pdfpages/mw1320.pdf
cp 'mwcolorpages/MW-main (coloured) 1321.pdf' pdfpages/mw1321.pdf
cp 'mwcolorpages/MW-main (coloured) 1322.pdf' pdfpages/mw1322.pdf
cp 'mwcolorpages/MW-main (coloured) 1323.pdf' pdfpages/mw1323.pdf
cp 'mwcolorpages/MW-main (coloured) 1324.pdf' pdfpages/mw1324.pdf
cp 'mwcolorpages/MW-main (coloured) 1325.pdf' pdfpages/mw1325.pdf
cp 'mwcolorpages/MW-main (coloured) 1326.pdf' pdfpages/mw1326.pdf
cp 'mwcolorpages/MW-main (coloured) 1327.pdf' pdfpages/mw1327.pdf
cp 'mwcolorpages/MW-main (coloured) 1328.pdf' pdfpages/mw1328.pdf
cp 'mwcolorpages/MW-main (coloured) 1329.pdf' pdfpages/mw1329.pdf
cp 'mwcolorpages/MW-main (coloured) 133.pdf' pdfpages/mw0133-AjAtazAtrava.pdf
cp 'mwcolorpages/MW-main (coloured) 1330.pdf' pdfpages/mw1330.pdf
cp 'mwcolorpages/MW-main (coloured) 1331.pdf' pdfpages/mw1331.pdf
cp 'mwcolorpages/MW-main (coloured) 1332.pdf' pdfpages/mw1332.pdf
cp 'mwcolorpages/MW-main (coloured) 1333.pdf' pdfpages/mw1333.pdf
cp 'mwcolorpages/MW-main (coloured) 134.pdf' pdfpages/mw0134-ADambarAghAta.pdf
cp 'mwcolorpages/MW-main (coloured) 135.pdf' pdfpages/mw0135-Atuc.pdf
cp 'mwcolorpages/MW-main (coloured) 136.pdf' pdfpages/mw0136-Atmahanana.pdf
cp 'mwcolorpages/MW-main (coloured) 137.pdf' pdfpages/mw0137-Adikavi.pdf
cp 'mwcolorpages/MW-main (coloured) 138.pdf' pdfpages/mw0138-AdR.pdf
cp 'mwcolorpages/MW-main (coloured) 139.pdf' pdfpages/mw0139-AdhI.pdf
cp 'mwcolorpages/MW-main (coloured) 14.pdf' pdfpages/mw0014-atitRd.pdf
cp 'mwcolorpages/MW-main (coloured) 140.pdf' pdfpages/mw0140-AnandakalikA.pdf
cp 'mwcolorpages/MW-main (coloured) 141.pdf' pdfpages/mw0141-AnucAraka.pdf
cp 'mwcolorpages/MW-main (coloured) 142.pdf' pdfpages/mw0142-Antarvedika.pdf
cp 'mwcolorpages/MW-main (coloured) 143.pdf' pdfpages/mw0143-ApaduddharaNa.pdf
cp 'mwcolorpages/MW-main (coloured) 144.pdf' pdfpages/mw0144-Apodevata.pdf
cp 'mwcolorpages/MW-main (coloured) 145.pdf' pdfpages/mw0145-Abayu.pdf
cp 'mwcolorpages/MW-main (coloured) 146.pdf' pdfpages/mw0146-AbhUS.pdf
cp 'mwcolorpages/MW-main (coloured) 147.pdf' pdfpages/mw0147-Amizratva.pdf
cp 'mwcolorpages/MW-main (coloured) 148.pdf' pdfpages/mw0148-Ayadarzin.pdf
cp 'mwcolorpages/MW-main (coloured) 149.pdf' pdfpages/mw0149-Ayurvedika.pdf
cp 'mwcolorpages/MW-main (coloured) 15.pdf' pdfpages/mw0015-atibRh.pdf
cp 'mwcolorpages/MW-main (coloured) 150.pdf' pdfpages/mw0150-AraNyakagAna.pdf
cp 'mwcolorpages/MW-main (coloured) 151.pdf' pdfpages/mw0151-Arudh.pdf
cp 'mwcolorpages/MW-main (coloured) 152.pdf' pdfpages/mw0152-ArtveyI.pdf
cp 'mwcolorpages/MW-main (coloured) 153.pdf' pdfpages/mw0153-AliGgitavat.pdf
cp 'mwcolorpages/MW-main (coloured) 154.pdf' pdfpages/mw0154-ArSeyavat.pdf
cp 'mwcolorpages/MW-main (coloured) 155.pdf' pdfpages/mw0155-Avarjaka.pdf
cp 'mwcolorpages/MW-main (coloured) 156.pdf' pdfpages/mw0156-AvIracUrNa.pdf
cp 'mwcolorpages/MW-main (coloured) 157.pdf' pdfpages/mw0157-Avraska.pdf
cp 'mwcolorpages/MW-main (coloured) 158.pdf' pdfpages/mw0158-AzuzuSkatva.pdf
cp 'mwcolorpages/MW-main (coloured) 159.pdf' pdfpages/mw0159-AzliSTa.pdf
cp 'mwcolorpages/MW-main (coloured) 16.pdf' pdfpages/mw0016-atiSakta.pdf
cp 'mwcolorpages/MW-main (coloured) 160.pdf' pdfpages/mw0160-Asyadaghna.pdf
cp 'mwcolorpages/MW-main (coloured) 161.pdf' pdfpages/mw0161-Asava.pdf
cp 'mwcolorpages/MW-main (coloured) 162.pdf' pdfpages/mw0162-AsyA.pdf
cp 'mwcolorpages/MW-main (coloured) 163.pdf' pdfpages/mw0163-AhAraniHsaraNamArga.pdf
cp 'mwcolorpages/MW-main (coloured) 164.pdf' pdfpages/mw0164-ikSupattra.pdf
cp 'mwcolorpages/MW-main (coloured) 165.pdf' pdfpages/mw0165-itaretarAzraya.pdf
cp 'mwcolorpages/MW-main (coloured) 166.pdf' pdfpages/mw0166-indirAlaya.pdf
cp 'mwcolorpages/MW-main (coloured) 167.pdf' pdfpages/mw0167-indravAh.pdf
cp 'mwcolorpages/MW-main (coloured) 168.pdf' pdfpages/mw0168-imaka.pdf
cp 'mwcolorpages/MW-main (coloured) 169.pdf' pdfpages/mw0169-iSukAra.pdf
cp 'mwcolorpages/MW-main (coloured) 17.pdf' pdfpages/mw0017-atyantasaMyoga.pdf
cp 'mwcolorpages/MW-main (coloured) 170.pdf' pdfpages/mw0170-ihakAra.pdf
cp 'mwcolorpages/MW-main (coloured) 171.pdf' pdfpages/mw0171-IL.pdf
cp 'mwcolorpages/MW-main (coloured) 172.pdf' pdfpages/mw0172-ukti.pdf
cp 'mwcolorpages/MW-main (coloured) 173.pdf' pdfpages/mw0173-uccabhASaNa.pdf
cp 'mwcolorpages/MW-main (coloured) 174.pdf' pdfpages/mw0174-ucchiSTakalpanA.pdf
cp 'mwcolorpages/MW-main (coloured) 175.pdf' pdfpages/mw0175-ujjha.pdf
cp 'mwcolorpages/MW-main (coloured) 176.pdf' pdfpages/mw0176-utkartana.pdf
cp 'mwcolorpages/MW-main (coloured) 177.pdf' pdfpages/mw0177-utkramajyA.pdf
cp 'mwcolorpages/MW-main (coloured) 178.pdf' pdfpages/mw0178-uttamazloka.pdf
cp 'mwcolorpages/MW-main (coloured) 179.pdf' pdfpages/mw0179-uttarAsaGga.pdf
cp 'mwcolorpages/MW-main (coloured) 18.pdf' pdfpages/mw0018-adakSiNatva.pdf
cp 'mwcolorpages/MW-main (coloured) 180.pdf' pdfpages/mw0180-utthAnayukta.pdf
cp 'mwcolorpages/MW-main (coloured) 181.pdf' pdfpages/mw0181-utpalabhedyaka.pdf
cp 'mwcolorpages/MW-main (coloured) 182.pdf' pdfpages/mw0182-utsad.pdf
cp 'mwcolorpages/MW-main (coloured) 183.pdf' pdfpages/mw0183-utsthala.pdf
cp 'mwcolorpages/MW-main (coloured) 184.pdf' pdfpages/mw0184-udak.pdf
cp 'mwcolorpages/MW-main (coloured) 185.pdf' pdfpages/mw0185-udavasAnIya.pdf
cp 'mwcolorpages/MW-main (coloured) 186.pdf' pdfpages/mw0186-udaya.pdf
cp 'mwcolorpages/MW-main (coloured) 187.pdf' pdfpages/mw0187-udgatazRGga.pdf
cp 'mwcolorpages/MW-main (coloured) 188.pdf' pdfpages/mw0188-uddaNDapAla.pdf
cp 'mwcolorpages/MW-main (coloured) 189.pdf' pdfpages/mw0189-uddhavadUta.pdf
cp 'mwcolorpages/MW-main (coloured) 19.pdf' pdfpages/mw0019-adevRghnI.pdf
cp 'mwcolorpages/MW-main (coloured) 190.pdf' pdfpages/mw0190-udbadhya.pdf
cp 'mwcolorpages/MW-main (coloured) 191.pdf' pdfpages/mw0191-udyantR.pdf
cp 'mwcolorpages/MW-main (coloured) 192.pdf' pdfpages/mw0192-udvAhika.pdf
cp 'mwcolorpages/MW-main (coloured) 193.pdf' pdfpages/mw0193-udhan.pdf
cp 'mwcolorpages/MW-main (coloured) 194.pdf' pdfpages/mw0194-unmadiSNu.pdf
cp 'mwcolorpages/MW-main (coloured) 195.pdf' pdfpages/mw0195-upaka.pdf
cp 'mwcolorpages/MW-main (coloured) 196.pdf' pdfpages/mw0196-upakosala.pdf
cp 'mwcolorpages/MW-main (coloured) 197.pdf' pdfpages/mw0197-upagAtR.pdf
cp 'mwcolorpages/MW-main (coloured) 198.pdf' pdfpages/mw0198-upajagatI.pdf
cp 'mwcolorpages/MW-main (coloured) 199.pdf' pdfpages/mw0199-upadagdha.pdf
cp 'mwcolorpages/MW-main (coloured) 2.pdf' pdfpages/mw0002-akarman.pdf
cp 'mwcolorpages/MW-main (coloured) 20.pdf' pdfpages/mw0020-adharAk.pdf
cp 'mwcolorpages/MW-main (coloured) 200.pdf' pdfpages/mw0200-upadhAtu.pdf
cp 'mwcolorpages/MW-main (coloured) 201.pdf' pdfpages/mw0201-upaniviSTa.pdf
cp 'mwcolorpages/MW-main (coloured) 202.pdf' pdfpages/mw0202-upapAduka.pdf
cp 'mwcolorpages/MW-main (coloured) 203.pdf' pdfpages/mw0203-upabindu.pdf
cp 'mwcolorpages/MW-main (coloured) 204.pdf' pdfpages/mw0204-upamukham.pdf
cp 'mwcolorpages/MW-main (coloured) 205.pdf' pdfpages/mw0205-uparAma.pdf
cp 'mwcolorpages/MW-main (coloured) 206.pdf' pdfpages/mw0206-upalabhya.pdf
cp 'mwcolorpages/MW-main (coloured) 207.pdf' pdfpages/mw0207-upavidh.pdf
cp 'mwcolorpages/MW-main (coloured) 208.pdf' pdfpages/mw0208-upazalyaka.pdf
cp 'mwcolorpages/MW-main (coloured) 209.pdf' pdfpages/mw0209-upasaMklRp.pdf
cp 'mwcolorpages/MW-main (coloured) 21.pdf' pdfpages/mw0021-adhigamana.pdf
cp 'mwcolorpages/MW-main (coloured) 210.pdf' pdfpages/mw0210-upasaMprAp.pdf
cp 'mwcolorpages/MW-main (coloured) 211.pdf' pdfpages/mw0211-upastara.pdf
cp 'mwcolorpages/MW-main (coloured) 212.pdf' pdfpages/mw0212-upahatnu.pdf
cp 'mwcolorpages/MW-main (coloured) 213.pdf' pdfpages/mw0213-upAgra.pdf
cp 'mwcolorpages/MW-main (coloured) 214.pdf' pdfpages/mw0214-upApa.pdf
cp 'mwcolorpages/MW-main (coloured) 215.pdf' pdfpages/mw0215-upAsana.pdf
cp 'mwcolorpages/MW-main (coloured) 216.pdf' pdfpages/mw0216-upendhya.pdf
cp 'mwcolorpages/MW-main (coloured) 217.pdf' pdfpages/mw0217-ubhayatoGga.pdf
cp 'mwcolorpages/MW-main (coloured) 218.pdf' pdfpages/mw0218-urudhiSNya.pdf
cp 'mwcolorpages/MW-main (coloured) 219.pdf' pdfpages/mw0219-ulkuSI.pdf
cp 'mwcolorpages/MW-main (coloured) 22.pdf' pdfpages/mw0022-adhivAka.pdf
cp 'mwcolorpages/MW-main (coloured) 220.pdf' pdfpages/mw0220-uzIragiri.pdf
cp 'mwcolorpages/MW-main (coloured) 221.pdf' pdfpages/mw0221-uhAna.pdf
cp 'mwcolorpages/MW-main (coloured) 222.pdf' pdfpages/mw0222-UrNAvat.pdf
cp 'mwcolorpages/MW-main (coloured) 223.pdf' pdfpages/mw0223-UrvarA.pdf
cp 'mwcolorpages/MW-main (coloured) 224.pdf' pdfpages/mw0224-RtaspRz.pdf
cp 'mwcolorpages/MW-main (coloured) 225.pdf' pdfpages/mw0225-RGga.pdf
cp 'mwcolorpages/MW-main (coloured) 226.pdf' pdfpages/mw0226-RNajya.pdf
cp 'mwcolorpages/MW-main (coloured) 227.pdf' pdfpages/mw0227-RSikalpa.pdf
cp 'mwcolorpages/MW-main (coloured) 228.pdf' pdfpages/mw0228-ekacittIbhU.pdf
cp 'mwcolorpages/MW-main (coloured) 229.pdf' pdfpages/mw0229-ekabhojin.pdf
cp 'mwcolorpages/MW-main (coloured) 23.pdf' pdfpages/mw0023-adhunAtana.pdf
cp 'mwcolorpages/MW-main (coloured) 230.pdf' pdfpages/mw0230-ekAkSarIbhAva.pdf
cp 'mwcolorpages/MW-main (coloured) 231.pdf' pdfpages/mw0231-ekata.pdf
cp 'mwcolorpages/MW-main (coloured) 232.pdf' pdfpages/mw0232-edhavat.pdf
cp 'mwcolorpages/MW-main (coloured) 233.pdf' pdfpages/mw0233-eSya.pdf
cp 'mwcolorpages/MW-main (coloured) 234.pdf' pdfpages/mw0234-aitizAyana.pdf
cp 'mwcolorpages/MW-main (coloured) 235.pdf' pdfpages/mw0235-aizvaryavivaraNa.pdf
cp 'mwcolorpages/MW-main (coloured) 236.pdf' pdfpages/mw0236-omkArIya.pdf
cp 'mwcolorpages/MW-main (coloured) 237.pdf' pdfpages/mw0237-auttara.pdf
cp 'mwcolorpages/MW-main (coloured) 238.pdf' pdfpages/mw0238-audbhaTa.pdf
cp 'mwcolorpages/MW-main (coloured) 239.pdf' pdfpages/mw0239-aupazamika.pdf
cp 'mwcolorpages/MW-main (coloured) 24.pdf' pdfpages/mw0024-adhva.pdf
cp 'mwcolorpages/MW-main (coloured) 240.pdf' pdfpages/mw0240-aurva.pdf
cp 'mwcolorpages/MW-main (coloured) 241.pdf' pdfpages/mw0241-kaMvUla.pdf
cp 'mwcolorpages/MW-main (coloured) 242.pdf' pdfpages/mw0242-kakSAzrita.pdf
cp 'mwcolorpages/MW-main (coloured) 243.pdf' pdfpages/mw0243-kacchapaka.pdf
cp 'mwcolorpages/MW-main (coloured) 244.pdf' pdfpages/mw0244-kaTizUla.pdf
cp 'mwcolorpages/MW-main (coloured) 245.pdf' pdfpages/mw0245-kaDandikA.pdf
cp 'mwcolorpages/MW-main (coloured) 246.pdf' pdfpages/mw0246-kaNThAvasakta.pdf
cp 'mwcolorpages/MW-main (coloured) 247.pdf' pdfpages/mw0247-katr.pdf
cp 'mwcolorpages/MW-main (coloured) 248.pdf' pdfpages/mw0248-kadAcAra.pdf
cp 'mwcolorpages/MW-main (coloured) 249.pdf' pdfpages/mw0249-kanIyastva.pdf
cp 'mwcolorpages/MW-main (coloured) 25.pdf' pdfpages/mw0025-ananRta.pdf
cp 'mwcolorpages/MW-main (coloured) 250.pdf' pdfpages/mw0250-kandalI.pdf
cp 'mwcolorpages/MW-main (coloured) 251.pdf' pdfpages/mw0251-kapilagItA.pdf
cp 'mwcolorpages/MW-main (coloured) 252.pdf' pdfpages/mw0252-kaMvat.pdf
cp 'mwcolorpages/MW-main (coloured) 253.pdf' pdfpages/mw0253-kambalya.pdf
cp 'mwcolorpages/MW-main (coloured) 254.pdf' pdfpages/mw0254-karodaka.pdf
cp 'mwcolorpages/MW-main (coloured) 255.pdf' pdfpages/mw0255-karaTa.pdf
cp 'mwcolorpages/MW-main (coloured) 256.pdf' pdfpages/mw0256-karkakhaNDa.pdf
cp 'mwcolorpages/MW-main (coloured) 257.pdf' pdfpages/mw0257-karNaprakAza.pdf
cp 'mwcolorpages/MW-main (coloured) 258.pdf' pdfpages/mw0258-kartRguptaka.pdf
cp 'mwcolorpages/MW-main (coloured) 259.pdf' pdfpages/mw0259-karmadhAraya.pdf
cp 'mwcolorpages/MW-main (coloured) 26.pdf' pdfpages/mw0026-anapsaras.pdf
cp 'mwcolorpages/MW-main (coloured) 260.pdf' pdfpages/mw0260-karSaphala.pdf
cp 'mwcolorpages/MW-main (coloured) 261.pdf' pdfpages/mw0261-kalazapotaka.pdf
cp 'mwcolorpages/MW-main (coloured) 262.pdf' pdfpages/mw0262-kalikAra.pdf
cp 'mwcolorpages/MW-main (coloured) 263.pdf' pdfpages/mw0263-kalpAntara.pdf
cp 'mwcolorpages/MW-main (coloured) 264.pdf' pdfpages/mw0264-kavaka.pdf
cp 'mwcolorpages/MW-main (coloured) 265.pdf' pdfpages/mw0265-kavya.pdf
cp 'mwcolorpages/MW-main (coloured) 266.pdf' pdfpages/mw0266-kaSTakara.pdf
cp 'mwcolorpages/MW-main (coloured) 267.pdf' pdfpages/mw0267-kAkatuNDaka.pdf
cp 'mwcolorpages/MW-main (coloured) 268.pdf' pdfpages/mw0268-kAkocika.pdf
cp 'mwcolorpages/MW-main (coloured) 269.pdf' pdfpages/mw0269-kAJcIpura.pdf
cp 'mwcolorpages/MW-main (coloured) 27.pdf' pdfpages/mw0027-anavarata.pdf
cp 'mwcolorpages/MW-main (coloured) 270.pdf' pdfpages/mw0270-kAtantra.pdf
cp 'mwcolorpages/MW-main (coloured) 271.pdf' pdfpages/mw0271-kAntika.pdf
cp 'mwcolorpages/MW-main (coloured) 272.pdf' pdfpages/mw0272-kAmakalikA.pdf
cp 'mwcolorpages/MW-main (coloured) 273.pdf' pdfpages/mw0273-kAmAdhikAra.pdf
cp 'mwcolorpages/MW-main (coloured) 274.pdf' pdfpages/mw0274-kAmbalika.pdf
cp 'mwcolorpages/MW-main (coloured) 275.pdf' pdfpages/mw0275-kAramihikA.pdf
cp 'mwcolorpages/MW-main (coloured) 276.pdf' pdfpages/mw0276-kArpAsatAntava.pdf
cp 'mwcolorpages/MW-main (coloured) 277.pdf' pdfpages/mw0277-kArSNi.pdf
cp 'mwcolorpages/MW-main (coloured) 278.pdf' pdfpages/mw0278-kAlikAmukha.pdf
cp 'mwcolorpages/MW-main (coloured) 279.pdf' pdfpages/mw0279-kAlasAhvaya.pdf
cp 'mwcolorpages/MW-main (coloured) 28.pdf' pdfpages/mw0028-anAda.pdf
cp 'mwcolorpages/MW-main (coloured) 280.pdf' pdfpages/mw0280-kAlvAla.pdf
cp 'mwcolorpages/MW-main (coloured) 281.pdf' pdfpages/mw0281-kAzmIraka.pdf
cp 'mwcolorpages/MW-main (coloured) 282.pdf' pdfpages/mw0282-kAhAraka.pdf
cp 'mwcolorpages/MW-main (coloured) 283.pdf' pdfpages/mw0283-kiMsuhRd.pdf
cp 'mwcolorpages/MW-main (coloured) 284.pdf' pdfpages/mw0284-kirAtatiktaka.pdf
cp 'mwcolorpages/MW-main (coloured) 285.pdf' pdfpages/mw0285-kITAri.pdf
cp 'mwcolorpages/MW-main (coloured) 286.pdf' pdfpages/mw0286-kutanu.pdf
cp 'mwcolorpages/MW-main (coloured) 287.pdf' pdfpages/mw0287-kuMza.pdf
cp 'mwcolorpages/MW-main (coloured) 288.pdf' pdfpages/mw0288-kuJcita.pdf
cp 'mwcolorpages/MW-main (coloured) 289.pdf' pdfpages/mw0289-kuTTita.pdf
cp 'mwcolorpages/MW-main (coloured) 29.pdf' pdfpages/mw0029-anAza.pdf
cp 'mwcolorpages/MW-main (coloured) 290.pdf' pdfpages/mw0290-kuNDIvRSa.pdf
cp 'mwcolorpages/MW-main (coloured) 291.pdf' pdfpages/mw0291-kudri.pdf
cp 'mwcolorpages/MW-main (coloured) 292.pdf' pdfpages/mw0292-kubjikA.pdf
cp 'mwcolorpages/MW-main (coloured) 293.pdf' pdfpages/mw0293-kumbh.pdf
cp 'mwcolorpages/MW-main (coloured) 294.pdf' pdfpages/mw0294-kurI.pdf
cp 'mwcolorpages/MW-main (coloured) 295.pdf' pdfpages/mw0295-kulaMdhara.pdf
cp 'mwcolorpages/MW-main (coloured) 296.pdf' pdfpages/mw0296-kulAyin.pdf
cp 'mwcolorpages/MW-main (coloured) 297.pdf' pdfpages/mw0297-kuzakAzamaya.pdf
cp 'mwcolorpages/MW-main (coloured) 298.pdf' pdfpages/mw0298-kuSThacikitsita.pdf
cp 'mwcolorpages/MW-main (coloured) 299.pdf' pdfpages/mw0299-kuhara.pdf
cp 'mwcolorpages/MW-main (coloured) 3.pdf' pdfpages/mw0003-akriya.pdf
cp 'mwcolorpages/MW-main (coloured) 30.pdf' pdfpages/mw0030-aniruktagAna.pdf
cp 'mwcolorpages/MW-main (coloured) 300.pdf' pdfpages/mw0300-kUdara.pdf
cp 'mwcolorpages/MW-main (coloured) 301.pdf' pdfpages/mw0301-kR.pdf
cp 'mwcolorpages/MW-main (coloured) 302.pdf' pdfpages/mw0302-kRtakAla.pdf
cp 'mwcolorpages/MW-main (coloured) 303.pdf' pdfpages/mw0303-kRtAgaska.pdf
cp 'mwcolorpages/MW-main (coloured) 304.pdf' pdfpages/mw0304-kRtrimaputraka.pdf
cp 'mwcolorpages/MW-main (coloured) 305.pdf' pdfpages/mw0305-kRtsnahRdaya.pdf
cp 'mwcolorpages/MW-main (coloured) 306.pdf' pdfpages/mw0306-kRzanAvat.pdf
cp 'mwcolorpages/MW-main (coloured) 307.pdf' pdfpages/mw0307-kRSNagarbha.pdf
cp 'mwcolorpages/MW-main (coloured) 308.pdf' pdfpages/mw0308-kRSNAgraja.pdf
cp 'mwcolorpages/MW-main (coloured) 309.pdf' pdfpages/mw0309-ketaki.pdf
cp 'mwcolorpages/MW-main (coloured) 31.pdf' pdfpages/mw0031-anIha.pdf
cp 'mwcolorpages/MW-main (coloured) 310.pdf' pdfpages/mw0310-kevalakarmin.pdf
cp 'mwcolorpages/MW-main (coloured) 311.pdf' pdfpages/mw0311-kesaragrAma.pdf
cp 'mwcolorpages/MW-main (coloured) 312.pdf' pdfpages/mw0312-kaizina.pdf
cp 'mwcolorpages/MW-main (coloured) 313.pdf' pdfpages/mw0313-koTTarAja.pdf
cp 'mwcolorpages/MW-main (coloured) 314.pdf' pdfpages/mw0314-kolyA.pdf
cp 'mwcolorpages/MW-main (coloured) 315.pdf' pdfpages/mw0315-kaukuNDihi.pdf
cp 'mwcolorpages/MW-main (coloured) 316.pdf' pdfpages/mw0316-kautuka.pdf
cp 'mwcolorpages/MW-main (coloured) 317.pdf' pdfpages/mw0317-kaumbhakAreya.pdf
cp 'mwcolorpages/MW-main (coloured) 318.pdf' pdfpages/mw0318-kauzalikA.pdf
cp 'mwcolorpages/MW-main (coloured) 319.pdf' pdfpages/mw0319-krakacapad.pdf
cp 'mwcolorpages/MW-main (coloured) 32.pdf' pdfpages/mw0032-anugavam.pdf
cp 'mwcolorpages/MW-main (coloured) 320.pdf' pdfpages/mw0320-kramapATha.pdf
cp 'mwcolorpages/MW-main (coloured) 321.pdf' pdfpages/mw0321-kriyAkANDa.pdf
cp 'mwcolorpages/MW-main (coloured) 322.pdf' pdfpages/mw0322-krIDu.pdf
cp 'mwcolorpages/MW-main (coloured) 323.pdf' pdfpages/mw0323-krUropasaMhata.pdf
cp 'mwcolorpages/MW-main (coloured) 324.pdf' pdfpages/mw0324-klizita.pdf
cp 'mwcolorpages/MW-main (coloured) 325.pdf' pdfpages/mw0325-kSaNakleza.pdf
cp 'mwcolorpages/MW-main (coloured) 326.pdf' pdfpages/mw0326-kSatavrata.pdf
cp 'mwcolorpages/MW-main (coloured) 327.pdf' pdfpages/mw0327-kSAmi.pdf
cp 'mwcolorpages/MW-main (coloured) 328.pdf' pdfpages/mw0328-kSitidevatA.pdf
cp 'mwcolorpages/MW-main (coloured) 329.pdf' pdfpages/mw0329-kSipa.pdf
cp 'mwcolorpages/MW-main (coloured) 33.pdf' pdfpages/mw0033-anutRR.pdf
cp 'mwcolorpages/MW-main (coloured) 330.pdf' pdfpages/mw0330-kSIravAri.pdf
cp 'mwcolorpages/MW-main (coloured) 331.pdf' pdfpages/mw0331-kSudravaidehI.pdf
cp 'mwcolorpages/MW-main (coloured) 332.pdf' pdfpages/mw0332-kSuramardin.pdf
cp 'mwcolorpages/MW-main (coloured) 333.pdf' pdfpages/mw0333-kSemabhUmi.pdf
cp 'mwcolorpages/MW-main (coloured) 334.pdf' pdfpages/mw0334-kSmApAla.pdf
cp 'mwcolorpages/MW-main (coloured) 335.pdf' pdfpages/mw0335-khaGkhaNa.pdf
cp 'mwcolorpages/MW-main (coloured) 336.pdf' pdfpages/mw0336-khaNDa.pdf
cp 'mwcolorpages/MW-main (coloured) 337.pdf' pdfpages/mw0337-khanI.pdf
cp 'mwcolorpages/MW-main (coloured) 338.pdf' pdfpages/mw0338-kharbUja.pdf
cp 'mwcolorpages/MW-main (coloured) 339.pdf' pdfpages/mw0339-khATvareya.pdf
cp 'mwcolorpages/MW-main (coloured) 34.pdf' pdfpages/mw0034-anunam.pdf
cp 'mwcolorpages/MW-main (coloured) 340.pdf' pdfpages/mw0340-khidira.pdf
cp 'mwcolorpages/MW-main (coloured) 341.pdf' pdfpages/mw0341-khoTi.pdf
cp 'mwcolorpages/MW-main (coloured) 342.pdf' pdfpages/mw0342-gaGguka.pdf
cp 'mwcolorpages/MW-main (coloured) 343.pdf' pdfpages/mw0343-gaNa.pdf
cp 'mwcolorpages/MW-main (coloured) 344.pdf' pdfpages/mw0344-gaNitin.pdf
cp 'mwcolorpages/MW-main (coloured) 345.pdf' pdfpages/mw0345-gandha.pdf
cp 'mwcolorpages/MW-main (coloured) 346.pdf' pdfpages/mw0346-gandharva.pdf
cp 'mwcolorpages/MW-main (coloured) 347.pdf' pdfpages/mw0347-gat.pdf
cp 'mwcolorpages/MW-main (coloured) 348.pdf' pdfpages/mw0348-gantva.pdf
cp 'mwcolorpages/MW-main (coloured) 349.pdf' pdfpages/mw0349-garud.pdf
cp 'mwcolorpages/MW-main (coloured) 35.pdf' pdfpages/mw0035-anupare.pdf
cp 'mwcolorpages/MW-main (coloured) 350.pdf' pdfpages/mw0350-garbhapuroDAza.pdf
cp 'mwcolorpages/MW-main (coloured) 351.pdf' pdfpages/mw0351-galacarman.pdf
cp 'mwcolorpages/MW-main (coloured) 352.pdf' pdfpages/mw0352-gavya.pdf
cp 'mwcolorpages/MW-main (coloured) 353.pdf' pdfpages/mw0353-gAyantikA.pdf
cp 'mwcolorpages/MW-main (coloured) 354.pdf' pdfpages/mw0354-gAmbhIrya.pdf
cp 'mwcolorpages/MW-main (coloured) 355.pdf' pdfpages/mw0355-gADhatA.pdf
cp 'mwcolorpages/MW-main (coloured) 356.pdf' pdfpages/mw0356-gilana.pdf
cp 'mwcolorpages/MW-main (coloured) 357.pdf' pdfpages/mw0357-guDUcikA.pdf
cp 'mwcolorpages/MW-main (coloured) 358.pdf' pdfpages/mw0358-guNasaMgraha.pdf
cp 'mwcolorpages/MW-main (coloured) 359.pdf' pdfpages/mw0359-gupta.pdf
cp 'mwcolorpages/MW-main (coloured) 36.pdf' pdfpages/mw0036-anupraroha.pdf
cp 'mwcolorpages/MW-main (coloured) 360.pdf' pdfpages/mw0360-guruvyatha.pdf
cp 'mwcolorpages/MW-main (coloured) 361.pdf' pdfpages/mw0361-gUdhacaturthapAdaprahelikA.pdf
cp 'mwcolorpages/MW-main (coloured) 362.pdf' pdfpages/mw0362-gRhakuliGga.pdf
cp 'mwcolorpages/MW-main (coloured) 363.pdf' pdfpages/mw0363-gRhu.pdf
cp 'mwcolorpages/MW-main (coloured) 364.pdf' pdfpages/mw0364-gokarNa.pdf
cp 'mwcolorpages/MW-main (coloured) 365.pdf' pdfpages/mw0365-godama.pdf
cp 'mwcolorpages/MW-main (coloured) 366.pdf' pdfpages/mw0366-gomata.pdf
cp 'mwcolorpages/MW-main (coloured) 367.pdf' pdfpages/mw0367-govindinI.pdf
cp 'mwcolorpages/MW-main (coloured) 368.pdf' pdfpages/mw0368-goda.pdf
cp 'mwcolorpages/MW-main (coloured) 369.pdf' pdfpages/mw0369-gozIrSa.pdf
cp 'mwcolorpages/MW-main (coloured) 37.pdf' pdfpages/mw0037-anumA.pdf
cp 'mwcolorpages/MW-main (coloured) 370.pdf' pdfpages/mw0370-gaurakRSNa.pdf
cp 'mwcolorpages/MW-main (coloured) 371.pdf' pdfpages/mw0371-grathila.pdf
cp 'mwcolorpages/MW-main (coloured) 372.pdf' pdfpages/mw0372-grabha.pdf
cp 'mwcolorpages/MW-main (coloured) 373.pdf' pdfpages/mw0373-grAhakakRkara.pdf
cp 'mwcolorpages/MW-main (coloured) 374.pdf' pdfpages/mw0374-grAmyakanda.pdf
cp 'mwcolorpages/MW-main (coloured) 375.pdf' pdfpages/mw0375-gha.pdf
cp 'mwcolorpages/MW-main (coloured) 376.pdf' pdfpages/mw0376-ghaNTApATali.pdf
cp 'mwcolorpages/MW-main (coloured) 377.pdf' pdfpages/mw0377-gharmatapta.pdf
cp 'mwcolorpages/MW-main (coloured) 378.pdf' pdfpages/mw0378-ghuS.pdf
cp 'mwcolorpages/MW-main (coloured) 379.pdf' pdfpages/mw0379-ghRtAdi.pdf
cp 'mwcolorpages/MW-main (coloured) 38.pdf' pdfpages/mw0038-anulApa.pdf
cp 'mwcolorpages/MW-main (coloured) 380.pdf' pdfpages/mw0380-ghrANacakSuz.pdf
cp 'mwcolorpages/MW-main (coloured) 381.pdf' pdfpages/mw0381-cakracUDAmaNi.pdf
cp 'mwcolorpages/MW-main (coloured) 382.pdf' pdfpages/mw0382-cakSa.pdf
cp 'mwcolorpages/MW-main (coloured) 383.pdf' pdfpages/mw0383-caTuka.pdf
cp 'mwcolorpages/MW-main (coloured) 384.pdf' pdfpages/mw0384-catuHzAla.pdf
cp 'mwcolorpages/MW-main (coloured) 385.pdf' pdfpages/mw0385-caturmuSTi.pdf
cp 'mwcolorpages/MW-main (coloured) 386.pdf' pdfpages/mw0386-catuSpAdaka.pdf
cp 'mwcolorpages/MW-main (coloured) 387.pdf' pdfpages/mw0387-candrakeza.pdf
cp 'mwcolorpages/MW-main (coloured) 388.pdf' pdfpages/mw0388-candrAmRtarasa.pdf
cp 'mwcolorpages/MW-main (coloured) 389.pdf' pdfpages/mw0389-campakavyavahArikathA.pdf
cp 'mwcolorpages/MW-main (coloured) 39.pdf' pdfpages/mw0039-anuviSTambha.pdf
cp 'mwcolorpages/MW-main (coloured) 390.pdf' pdfpages/mw0390-caritavya.pdf
cp 'mwcolorpages/MW-main (coloured) 391.pdf' pdfpages/mw0391-carmika.pdf
cp 'mwcolorpages/MW-main (coloured) 392.pdf' pdfpages/mw0392-cATigrAma.pdf
cp 'mwcolorpages/MW-main (coloured) 393.pdf' pdfpages/mw0393-cAndri.pdf
cp 'mwcolorpages/MW-main (coloured) 394.pdf' pdfpages/mw0394-cAruratha.pdf
cp 'mwcolorpages/MW-main (coloured) 395.pdf' pdfpages/mw0395-cikIrSya.pdf
cp 'mwcolorpages/MW-main (coloured) 396.pdf' pdfpages/mw0396-cittavibhrama.pdf
cp 'mwcolorpages/MW-main (coloured) 397.pdf' pdfpages/mw0397-citrayAna.pdf
cp 'mwcolorpages/MW-main (coloured) 398.pdf' pdfpages/mw0398-cetanIyA.pdf
cp 'mwcolorpages/MW-main (coloured) 399.pdf' pdfpages/mw0399-ciravRtta.pdf
cp 'mwcolorpages/MW-main (coloured) 4.pdf' pdfpages/mw0004-akSika.pdf
cp 'mwcolorpages/MW-main (coloured) 40.pdf' pdfpages/mw0040-anuSaGgika.pdf
cp 'mwcolorpages/MW-main (coloured) 400.pdf' pdfpages/mw0400-cukraka.pdf
cp 'mwcolorpages/MW-main (coloured) 401.pdf' pdfpages/mw0401-cUDaka.pdf
cp 'mwcolorpages/MW-main (coloured) 402.pdf' pdfpages/mw0402-cera.pdf
cp 'mwcolorpages/MW-main (coloured) 403.pdf' pdfpages/mw0403-colamaNDala.pdf
cp 'mwcolorpages/MW-main (coloured) 404.pdf' pdfpages/mw0404-cyUta.pdf
cp 'mwcolorpages/MW-main (coloured) 405.pdf' pdfpages/mw0405-chandapAtana.pdf
cp 'mwcolorpages/MW-main (coloured) 406.pdf' pdfpages/mw0406-chAta.pdf
cp 'mwcolorpages/MW-main (coloured) 407.pdf' pdfpages/mw0407-chinnaka.pdf
cp 'mwcolorpages/MW-main (coloured) 408.pdf' pdfpages/mw0408-jagat.pdf
cp 'mwcolorpages/MW-main (coloured) 409.pdf' pdfpages/mw0409-jaGgalapatha.pdf
cp 'mwcolorpages/MW-main (coloured) 41.pdf' pdfpages/mw0041-anusambaddha.pdf
cp 'mwcolorpages/MW-main (coloured) 410.pdf' pdfpages/mw0410-jatugeha.pdf
cp 'mwcolorpages/MW-main (coloured) 411.pdf' pdfpages/mw0411-jananAntara.pdf
cp 'mwcolorpages/MW-main (coloured) 412.pdf' pdfpages/mw0412-japa.pdf
cp 'mwcolorpages/MW-main (coloured) 413.pdf' pdfpages/mw0413-jayakarNa.pdf
cp 'mwcolorpages/MW-main (coloured) 414.pdf' pdfpages/mw0414-jaratpittazUla.pdf
cp 'mwcolorpages/MW-main (coloured) 415.pdf' pdfpages/mw0415-jaladardura.pdf
cp 'mwcolorpages/MW-main (coloured) 416.pdf' pdfpages/mw0416-jalArdrikA.pdf
cp 'mwcolorpages/MW-main (coloured) 417.pdf' pdfpages/mw0417-jAgR.pdf
cp 'mwcolorpages/MW-main (coloured) 418.pdf' pdfpages/mw0418-jAtodaka.pdf
cp 'mwcolorpages/MW-main (coloured) 419.pdf' pdfpages/mw0419-jAnevAdika.pdf
cp 'mwcolorpages/MW-main (coloured) 42.pdf' pdfpages/mw0042-anUnavarcas.pdf
cp 'mwcolorpages/MW-main (coloured) 420.pdf' pdfpages/mw0420-jAlakAra.pdf
cp 'mwcolorpages/MW-main (coloured) 421.pdf' pdfpages/mw0421-jighAMsA.pdf
cp 'mwcolorpages/MW-main (coloured) 422.pdf' pdfpages/mw0422-jihmita.pdf
cp 'mwcolorpages/MW-main (coloured) 423.pdf' pdfpages/mw0423-jIvamizra.pdf
cp 'mwcolorpages/MW-main (coloured) 424.pdf' pdfpages/mw0424-jUrNAhva.pdf
cp 'mwcolorpages/MW-main (coloured) 425.pdf' pdfpages/mw0425-jehila.pdf
cp 'mwcolorpages/MW-main (coloured) 426.pdf' pdfpages/mw0426-jJAtivid.pdf
cp 'mwcolorpages/MW-main (coloured) 427.pdf' pdfpages/mw0427-jyeSThatA.pdf
cp 'mwcolorpages/MW-main (coloured) 428.pdf' pdfpages/mw0428-jyotsnAkAlI.pdf
cp 'mwcolorpages/MW-main (coloured) 429.pdf' pdfpages/mw0429-jhallakaNTha.pdf
cp 'mwcolorpages/MW-main (coloured) 43.pdf' pdfpages/mw0043-antavat.pdf
cp 'mwcolorpages/MW-main (coloured) 430.pdf' pdfpages/mw0430-TIkA.pdf
cp 'mwcolorpages/MW-main (coloured) 431.pdf' pdfpages/mw0431-DuDubha.pdf
cp 'mwcolorpages/MW-main (coloured) 432.pdf' pdfpages/mw0432-tagaraka.pdf
cp 'mwcolorpages/MW-main (coloured) 433.pdf' pdfpages/mw0433-tatpada.pdf
cp 'mwcolorpages/MW-main (coloured) 434.pdf' pdfpages/mw0434-tathotsAha.pdf
cp 'mwcolorpages/MW-main (coloured) 435.pdf' pdfpages/mw0435-tallakSaNa.pdf
cp 'mwcolorpages/MW-main (coloured) 436.pdf' pdfpages/mw0436-tanUhrada.pdf
cp 'mwcolorpages/MW-main (coloured) 437.pdf' pdfpages/mw0437-tapAnta.pdf
cp 'mwcolorpages/MW-main (coloured) 438.pdf' pdfpages/mw0438-tam.pdf
cp 'mwcolorpages/MW-main (coloured) 439.pdf' pdfpages/mw0439-taraNIya.pdf
cp 'mwcolorpages/MW-main (coloured) 44.pdf' pdfpages/mw0044-antaraprabhava.pdf
cp 'mwcolorpages/MW-main (coloured) 440.pdf' pdfpages/mw0440-tarkajJAna.pdf
cp 'mwcolorpages/MW-main (coloured) 441.pdf' pdfpages/mw0441-talukSa.pdf
cp 'mwcolorpages/MW-main (coloured) 442.pdf' pdfpages/mw0442-tAtagu.pdf
cp 'mwcolorpages/MW-main (coloured) 443.pdf' pdfpages/mw0443-tAmasakIlaka.pdf
cp 'mwcolorpages/MW-main (coloured) 444.pdf' pdfpages/mw0444-tAramAkSika.pdf
cp 'mwcolorpages/MW-main (coloured) 445.pdf' pdfpages/mw0445-tAlaketu.pdf
cp 'mwcolorpages/MW-main (coloured) 446.pdf' pdfpages/mw0446-tAvISa.pdf
cp 'mwcolorpages/MW-main (coloured) 447.pdf' pdfpages/mw0447-tinduki.pdf
cp 'mwcolorpages/MW-main (coloured) 448.pdf' pdfpages/mw0448-tiryadryaJc.pdf
cp 'mwcolorpages/MW-main (coloured) 449.pdf' pdfpages/mw0449-tIkSNapriya.pdf
cp 'mwcolorpages/MW-main (coloured) 45.pdf' pdfpages/mw0045-andhatAmisra.pdf
cp 'mwcolorpages/MW-main (coloured) 450.pdf' pdfpages/mw0450-tuGganAsikA.pdf
cp 'mwcolorpages/MW-main (coloured) 451.pdf' pdfpages/mw0451-turagAtu.pdf
cp 'mwcolorpages/MW-main (coloured) 452.pdf' pdfpages/mw0452-tuvikSatra.pdf
cp 'mwcolorpages/MW-main (coloured) 453.pdf' pdfpages/mw0453-tUSAdhAna.pdf
cp 'mwcolorpages/MW-main (coloured) 454.pdf' pdfpages/mw0454-tRpAya.pdf
cp 'mwcolorpages/MW-main (coloured) 455.pdf' pdfpages/mw0455-tep.pdf
cp 'mwcolorpages/MW-main (coloured) 456.pdf' pdfpages/mw0456-toya.pdf
cp 'mwcolorpages/MW-main (coloured) 457.pdf' pdfpages/mw0457-tyAgima.pdf
cp 'mwcolorpages/MW-main (coloured) 458.pdf' pdfpages/mw0458-trikakud.pdf
cp 'mwcolorpages/MW-main (coloured) 459.pdf' pdfpages/mw0459-tridhAtuka.pdf
cp 'mwcolorpages/MW-main (coloured) 46.pdf' pdfpages/mw0046-anyonya.pdf
cp 'mwcolorpages/MW-main (coloured) 460.pdf' pdfpages/mw0460-trimala.pdf
cp 'mwcolorpages/MW-main (coloured) 461.pdf' pdfpages/mw0461-trizila.pdf
cp 'mwcolorpages/MW-main (coloured) 462.pdf' pdfpages/mw0462-tripu.pdf
cp 'mwcolorpages/MW-main (coloured) 463.pdf' pdfpages/mw0463-tryaGgula.pdf
cp 'mwcolorpages/MW-main (coloured) 464.pdf' pdfpages/mw0464-tvara.pdf
cp 'mwcolorpages/MW-main (coloured) 465.pdf' pdfpages/mw0465-daMSTrAla.pdf
cp 'mwcolorpages/MW-main (coloured) 466.pdf' pdfpages/mw0466-dakSiNAzA.pdf
cp 'mwcolorpages/MW-main (coloured) 467.pdf' pdfpages/mw0467-daNDapiGgalaka.pdf
cp 'mwcolorpages/MW-main (coloured) 468.pdf' pdfpages/mw0468-dadari.pdf
cp 'mwcolorpages/MW-main (coloured) 469.pdf' pdfpages/mw0469-dantavAsas.pdf
cp 'mwcolorpages/MW-main (coloured) 47.pdf' pdfpages/mw0047-anvAdiz.pdf
cp 'mwcolorpages/MW-main (coloured) 470.pdf' pdfpages/mw0470-dayAkara.pdf
cp 'mwcolorpages/MW-main (coloured) 471.pdf' pdfpages/mw0471-darzanagriha.pdf
cp 'mwcolorpages/MW-main (coloured) 472.pdf' pdfpages/mw0472-dazapuraMdara.pdf
cp 'mwcolorpages/MW-main (coloured) 473.pdf' pdfpages/mw0473-dazasyA.pdf
cp 'mwcolorpages/MW-main (coloured) 474.pdf' pdfpages/mw0474-dA.pdf
cp 'mwcolorpages/MW-main (coloured) 475.pdf' pdfpages/mw0475-dAma.pdf
cp 'mwcolorpages/MW-main (coloured) 476.pdf' pdfpages/mw0476-dArakriyA.pdf
cp 'mwcolorpages/MW-main (coloured) 477.pdf' pdfpages/mw0477-dAzaratha.pdf
cp 'mwcolorpages/MW-main (coloured) 478.pdf' pdfpages/mw0478-didyotiSu.pdf
cp 'mwcolorpages/MW-main (coloured) 479.pdf' pdfpages/mw0479-divAkIrti.pdf
cp 'mwcolorpages/MW-main (coloured) 48.pdf' pdfpages/mw0048-apakIrti.pdf
cp 'mwcolorpages/MW-main (coloured) 480.pdf' pdfpages/mw0480-digantara.pdf
cp 'mwcolorpages/MW-main (coloured) 481.pdf' pdfpages/mw0481-dIkSAvinoda.pdf
cp 'mwcolorpages/MW-main (coloured) 482.pdf' pdfpages/mw0482-dIrghakUrca.pdf
cp 'mwcolorpages/MW-main (coloured) 483.pdf' pdfpages/mw0483-dut.pdf
cp 'mwcolorpages/MW-main (coloured) 484.pdf' pdfpages/mw0484-dugdhamukha.pdf
cp 'mwcolorpages/MW-main (coloured) 485.pdf' pdfpages/mw0485-durApa.pdf
cp 'mwcolorpages/MW-main (coloured) 486.pdf' pdfpages/mw0486-durpaddhita.pdf
cp 'mwcolorpages/MW-main (coloured) 487.pdf' pdfpages/mw0487-durvAsas.pdf
cp 'mwcolorpages/MW-main (coloured) 488.pdf' pdfpages/mw0488-duSTanu.pdf
cp 'mwcolorpages/MW-main (coloured) 489.pdf' pdfpages/mw0489-dUSaNAri.pdf
cp 'mwcolorpages/MW-main (coloured) 49.pdf' pdfpages/mw0049-apaTAntara.pdf
cp 'mwcolorpages/MW-main (coloured) 490.pdf' pdfpages/mw0490-dUrI.pdf
cp 'mwcolorpages/MW-main (coloured) 491.pdf' pdfpages/mw0491-dRgaJcala.pdf
cp 'mwcolorpages/MW-main (coloured) 492.pdf' pdfpages/mw0492-dRSTAriSTa.pdf
cp 'mwcolorpages/MW-main (coloured) 493.pdf' pdfpages/mw0493-devagAyana.pdf
cp 'mwcolorpages/MW-main (coloured) 494.pdf' pdfpages/mw0494-devabhU.pdf
cp 'mwcolorpages/MW-main (coloured) 495.pdf' pdfpages/mw0495-devasUda.pdf
cp 'mwcolorpages/MW-main (coloured) 496.pdf' pdfpages/mw0496-devala.pdf
cp 'mwcolorpages/MW-main (coloured) 497.pdf' pdfpages/mw0497-dehadhAraNa.pdf
cp 'mwcolorpages/MW-main (coloured) 498.pdf' pdfpages/mw0498-daivaka.pdf
cp 'mwcolorpages/MW-main (coloured) 499.pdf' pdfpages/mw0499-doH.pdf
cp 'mwcolorpages/MW-main (coloured) 5.pdf' pdfpages/mw0005-agUDha.pdf
cp 'mwcolorpages/MW-main (coloured) 50.pdf' pdfpages/mw0050-apapad.pdf
cp 'mwcolorpages/MW-main (coloured) 500.pdf' pdfpages/mw0500-dyAvAkSame.pdf
cp 'mwcolorpages/MW-main (coloured) 501.pdf' pdfpages/mw0501-dravadazva.pdf
cp 'mwcolorpages/MW-main (coloured) 502.pdf' pdfpages/mw0502-drAvayitnu.pdf
cp 'mwcolorpages/MW-main (coloured) 503.pdf' pdfpages/mw0503-droNakalaza.pdf
cp 'mwcolorpages/MW-main (coloured) 504.pdf' pdfpages/mw0504-dvAdazajyotirliGgastotra.pdf
cp 'mwcolorpages/MW-main (coloured) 505.pdf' pdfpages/mw0505-dvitriveNu.pdf
cp 'mwcolorpages/MW-main (coloured) 506.pdf' pdfpages/mw0506-dvizUla.pdf
cp 'mwcolorpages/MW-main (coloured) 507.pdf' pdfpages/mw0507-dviSatA.pdf
cp 'mwcolorpages/MW-main (coloured) 508.pdf' pdfpages/mw0508-dvyahIna.pdf
cp 'mwcolorpages/MW-main (coloured) 509.pdf' pdfpages/mw0509-dhanoSman.pdf
cp 'mwcolorpages/MW-main (coloured) 51.pdf' pdfpages/mw0051-aparAGmukha.pdf
cp 'mwcolorpages/MW-main (coloured) 510.pdf' pdfpages/mw0510-dhamani.pdf
cp 'mwcolorpages/MW-main (coloured) 511.pdf' pdfpages/mw0511-dharmakhaNDa.pdf
cp 'mwcolorpages/MW-main (coloured) 512.pdf' pdfpages/mw0512-dharmavAhana.pdf
cp 'mwcolorpages/MW-main (coloured) 513.pdf' pdfpages/mw0513-dharmitva.pdf
cp 'mwcolorpages/MW-main (coloured) 514.pdf' pdfpages/mw0514-dhAtucandrikA.pdf
cp 'mwcolorpages/MW-main (coloured) 515.pdf' pdfpages/mw0515-dhAnaka.pdf
cp 'mwcolorpages/MW-main (coloured) 516.pdf' pdfpages/mw0516-dhArAsalila.pdf
cp 'mwcolorpages/MW-main (coloured) 517.pdf' pdfpages/mw0517-dhIdA.pdf
cp 'mwcolorpages/MW-main (coloured) 518.pdf' pdfpages/mw0518-dhUpapAtra.pdf
cp 'mwcolorpages/MW-main (coloured) 519.pdf' pdfpages/mw0519-dhUrtalavaNa.pdf
cp 'mwcolorpages/MW-main (coloured) 52.pdf' pdfpages/mw0052-apalASuka.pdf
cp 'mwcolorpages/MW-main (coloured) 520.pdf' pdfpages/mw0520-dhRSTaketu.pdf
cp 'mwcolorpages/MW-main (coloured) 521.pdf' pdfpages/mw0521-dhmApita.pdf
cp 'mwcolorpages/MW-main (coloured) 522.pdf' pdfpages/mw0522-dhrauvaki.pdf
cp 'mwcolorpages/MW-main (coloured) 523.pdf' pdfpages/mw0523-dhvRt.pdf
cp 'mwcolorpages/MW-main (coloured) 524.pdf' pdfpages/mw0524-nakulatva.pdf
cp 'mwcolorpages/MW-main (coloured) 525.pdf' pdfpages/mw0525-naga.pdf
cp 'mwcolorpages/MW-main (coloured) 526.pdf' pdfpages/mw0526-natamUrdhan.pdf
cp 'mwcolorpages/MW-main (coloured) 527.pdf' pdfpages/mw0527-nandanakAnana.pdf
cp 'mwcolorpages/MW-main (coloured) 528.pdf' pdfpages/mw0528-nabhoyoni.pdf
cp 'mwcolorpages/MW-main (coloured) 529.pdf' pdfpages/mw0529-narakapAla.pdf
cp 'mwcolorpages/MW-main (coloured) 53.pdf' pdfpages/mw0053-apazvAsa.pdf
cp 'mwcolorpages/MW-main (coloured) 530.pdf' pdfpages/mw0530-nartitavya.pdf
cp 'mwcolorpages/MW-main (coloured) 531.pdf' pdfpages/mw0531-navama.pdf
cp 'mwcolorpages/MW-main (coloured) 532.pdf' pdfpages/mw0532-naz.pdf
cp 'mwcolorpages/MW-main (coloured) 533.pdf' pdfpages/mw0533-nAgakanda.pdf
cp 'mwcolorpages/MW-main (coloured) 534.pdf' pdfpages/mw0534-nAgarakhaNDa.pdf
cp 'mwcolorpages/MW-main (coloured) 535.pdf' pdfpages/mw0535-nAdita.pdf
cp 'mwcolorpages/MW-main (coloured) 536.pdf' pdfpages/mw0536-nAbhaka.pdf
cp 'mwcolorpages/MW-main (coloured) 537.pdf' pdfpages/mw0537-nArAyaNakaNTha.pdf
cp 'mwcolorpages/MW-main (coloured) 538.pdf' pdfpages/mw0538-nAlitA.pdf
cp 'mwcolorpages/MW-main (coloured) 539.pdf' pdfpages/mw0539-niHSaGga.pdf
cp 'mwcolorpages/MW-main (coloured) 54.pdf' pdfpages/mw0054-apAkariSNu.pdf
cp 'mwcolorpages/MW-main (coloured) 540.pdf' pdfpages/mw0540-nirazana.pdf
cp 'mwcolorpages/MW-main (coloured) 541.pdf' pdfpages/mw0541-nirgavAkSa.pdf
cp 'mwcolorpages/MW-main (coloured) 542.pdf' pdfpages/mw0542-niryatna.pdf
cp 'mwcolorpages/MW-main (coloured) 543.pdf' pdfpages/mw0543-niSkAraNa.pdf
cp 'mwcolorpages/MW-main (coloured) 544.pdf' pdfpages/mw0544-niHzas.pdf
cp 'mwcolorpages/MW-main (coloured) 545.pdf' pdfpages/mw0545-nikUla.pdf
cp 'mwcolorpages/MW-main (coloured) 546.pdf' pdfpages/mw0546-nigA.pdf
cp 'mwcolorpages/MW-main (coloured) 547.pdf' pdfpages/mw0547-nikta.pdf
cp 'mwcolorpages/MW-main (coloured) 548.pdf' pdfpages/mw0548-nidA.pdf
cp 'mwcolorpages/MW-main (coloured) 549.pdf' pdfpages/mw0549-nidhi.pdf
cp 'mwcolorpages/MW-main (coloured) 55.pdf' pdfpages/mw0055-apAsyat.pdf
cp 'mwcolorpages/MW-main (coloured) 550.pdf' pdfpages/mw0550-nipuNa.pdf
cp 'mwcolorpages/MW-main (coloured) 551.pdf' pdfpages/mw0551-nimantrya.pdf
cp 'mwcolorpages/MW-main (coloured) 552.pdf' pdfpages/mw0552-niyata.pdf
cp 'mwcolorpages/MW-main (coloured) 553.pdf' pdfpages/mw0553-niradh.pdf
cp 'mwcolorpages/MW-main (coloured) 554.pdf' pdfpages/mw0554-niruddha.pdf
cp 'mwcolorpages/MW-main (coloured) 555.pdf' pdfpages/mw0555-nirjhara.pdf
cp 'mwcolorpages/MW-main (coloured) 556.pdf' pdfpages/mw0556-nirbhartsana.pdf
cp 'mwcolorpages/MW-main (coloured) 557.pdf' pdfpages/mw0557-niryAmaka.pdf
cp 'mwcolorpages/MW-main (coloured) 558.pdf' pdfpages/mw0558-nirvivitsu.pdf
cp 'mwcolorpages/MW-main (coloured) 559.pdf' pdfpages/mw0559-nivadh.pdf
cp 'mwcolorpages/MW-main (coloured) 56.pdf' pdfpages/mw0056-apyayadIkSita.pdf
cp 'mwcolorpages/MW-main (coloured) 560.pdf' pdfpages/mw0560-nivRti.pdf
cp 'mwcolorpages/MW-main (coloured) 561.pdf' pdfpages/mw0561-nizaraNa.pdf
cp 'mwcolorpages/MW-main (coloured) 562.pdf' pdfpages/mw0562-niSadhAdhezvara.pdf
cp 'mwcolorpages/MW-main (coloured) 563.pdf' pdfpages/mw0563-niSkramaNita.pdf
cp 'mwcolorpages/MW-main (coloured) 564.pdf' pdfpages/mw0564-nisarga.pdf
cp 'mwcolorpages/MW-main (coloured) 565.pdf' pdfpages/mw0565-nihava.pdf
cp 'mwcolorpages/MW-main (coloured) 566.pdf' pdfpages/mw0566-nIra.pdf
cp 'mwcolorpages/MW-main (coloured) 567.pdf' pdfpages/mw0567-nIlAlikulasaMkula.pdf
cp 'mwcolorpages/MW-main (coloured) 568.pdf' pdfpages/mw0568-nRmaNas.pdf
cp 'mwcolorpages/MW-main (coloured) 569.pdf' pdfpages/mw0569-netrajala.pdf
cp 'mwcolorpages/MW-main (coloured) 57.pdf' pdfpages/mw0057-apauruSeya.pdf
cp 'mwcolorpages/MW-main (coloured) 570.pdf' pdfpages/mw0570-naipAtya.pdf
cp 'mwcolorpages/MW-main (coloured) 571.pdf' pdfpages/mw0571-naiyaGkava.pdf
cp 'mwcolorpages/MW-main (coloured) 572.pdf' pdfpages/mw0572-nyanta.pdf
cp 'mwcolorpages/MW-main (coloured) 573.pdf' pdfpages/mw0573-nyAviz.pdf
cp 'mwcolorpages/MW-main (coloured) 574.pdf' pdfpages/mw0574-pakSabala.pdf
cp 'mwcolorpages/MW-main (coloured) 575.pdf' pdfpages/mw0575-paGgUyita.pdf
cp 'mwcolorpages/MW-main (coloured) 576.pdf' pdfpages/mw0576-paJcagauDabrAhmaNajAti.pdf
cp 'mwcolorpages/MW-main (coloured) 577.pdf' pdfpages/mw0577-paJcamahAyajJa.pdf
cp 'mwcolorpages/MW-main (coloured) 578.pdf' pdfpages/mw0578-paJcAGguri.pdf
cp 'mwcolorpages/MW-main (coloured) 579.pdf' pdfpages/mw0579-paT.pdf
cp 'mwcolorpages/MW-main (coloured) 58.pdf' pdfpages/mw0058-apratiyatnapUrva.pdf
cp 'mwcolorpages/MW-main (coloured) 580.pdf' pdfpages/mw0580-paTTeraka.pdf
cp 'mwcolorpages/MW-main (coloured) 581.pdf' pdfpages/mw0581-pataM.pdf
cp 'mwcolorpages/MW-main (coloured) 582.pdf' pdfpages/mw0582-pattraya.pdf
cp 'mwcolorpages/MW-main (coloured) 583.pdf' pdfpages/mw0583-pat.pdf
cp 'mwcolorpages/MW-main (coloured) 584.pdf' pdfpages/mw0584-padAvagrAham.pdf
cp 'mwcolorpages/MW-main (coloured) 585.pdf' pdfpages/mw0585-padmalekhA.pdf
cp 'mwcolorpages/MW-main (coloured) 586.pdf' pdfpages/mw0586-payaspati.pdf
cp 'mwcolorpages/MW-main (coloured) 587.pdf' pdfpages/mw0587-parapArabhUta.pdf
cp 'mwcolorpages/MW-main (coloured) 588.pdf' pdfpages/mw0588-parAvasathazAyin.pdf
cp 'mwcolorpages/MW-main (coloured) 589.pdf' pdfpages/mw0589-parameSThina.pdf
cp 'mwcolorpages/MW-main (coloured) 59.pdf' pdfpages/mw0059-apravINa.pdf
cp 'mwcolorpages/MW-main (coloured) 590.pdf' pdfpages/mw0590-parAk.pdf
cp 'mwcolorpages/MW-main (coloured) 591.pdf' pdfpages/mw0591-parAvarta.pdf
cp 'mwcolorpages/MW-main (coloured) 592.pdf' pdfpages/mw0592-parikarSa.pdf
cp 'mwcolorpages/MW-main (coloured) 593.pdf' pdfpages/mw0593-pariguNita.pdf
cp 'mwcolorpages/MW-main (coloured) 594.pdf' pdfpages/mw0594-paricetavya.pdf
cp 'mwcolorpages/MW-main (coloured) 595.pdf' pdfpages/mw0595-pariNidhA.pdf
cp 'mwcolorpages/MW-main (coloured) 596.pdf' pdfpages/mw0596-paridRSTa.pdf
cp 'mwcolorpages/MW-main (coloured) 597.pdf' pdfpages/mw0597-paripanna.pdf
cp 'mwcolorpages/MW-main (coloured) 598.pdf' pdfpages/mw0598-paribAdh.pdf
cp 'mwcolorpages/MW-main (coloured) 599.pdf' pdfpages/mw0599-parimalaya.pdf
cp 'mwcolorpages/MW-main (coloured) 6.pdf' pdfpages/mw0006-agnisaMskAra.pdf
cp 'mwcolorpages/MW-main (coloured) 60.pdf' pdfpages/mw0060-abaddhaka.pdf
cp 'mwcolorpages/MW-main (coloured) 600.pdf' pdfpages/mw0600-parirAj.pdf
cp 'mwcolorpages/MW-main (coloured) 601.pdf' pdfpages/mw0601-parivindat.pdf
cp 'mwcolorpages/MW-main (coloured) 602.pdf' pdfpages/mw0602-pariveSTana.pdf
cp 'mwcolorpages/MW-main (coloured) 603.pdf' pdfpages/mw0603-pariSic.pdf
cp 'mwcolorpages/MW-main (coloured) 604.pdf' pdfpages/mw0604-parisAdhana.pdf
cp 'mwcolorpages/MW-main (coloured) 605.pdf' pdfpages/mw0605-parihAra.pdf
cp 'mwcolorpages/MW-main (coloured) 606.pdf' pdfpages/mw0606-paruSaghana.pdf
cp 'mwcolorpages/MW-main (coloured) 607.pdf' pdfpages/mw0607-paryagu.pdf
cp 'mwcolorpages/MW-main (coloured) 608.pdf' pdfpages/mw0608-paryANaya.pdf
cp 'mwcolorpages/MW-main (coloured) 609.pdf' pdfpages/mw0609-paryarSaNa.pdf
cp 'mwcolorpages/MW-main (coloured) 61.pdf' pdfpages/mw0061-abhAvanA.pdf
cp 'mwcolorpages/MW-main (coloured) 610.pdf' pdfpages/mw0610-palakyA.pdf
cp 'mwcolorpages/MW-main (coloured) 611.pdf' pdfpages/mw0611-pavamAnaTippana.pdf
cp 'mwcolorpages/MW-main (coloured) 612.pdf' pdfpages/mw0612-pazubandhaka.pdf
cp 'mwcolorpages/MW-main (coloured) 613.pdf' pdfpages/mw0613-pAtrakaTaka.pdf
cp 'mwcolorpages/MW-main (coloured) 614.pdf' pdfpages/mw0614-pAkakarmanibandha.pdf
cp 'mwcolorpages/MW-main (coloured) 615.pdf' pdfpages/mw0615-pATana.pdf
cp 'mwcolorpages/MW-main (coloured) 616.pdf' pdfpages/mw0616-pANinIyamatadarpaNa.pdf
cp 'mwcolorpages/MW-main (coloured) 617.pdf' pdfpages/mw0617-pAtuka.pdf
cp 'mwcolorpages/MW-main (coloured) 618.pdf' pdfpages/mw0618-pAdAntara.pdf
cp 'mwcolorpages/MW-main (coloured) 619.pdf' pdfpages/mw0619-pApAtman.pdf
cp 'mwcolorpages/MW-main (coloured) 62.pdf' pdfpages/mw0062-abhigRhIta.pdf
cp 'mwcolorpages/MW-main (coloured) 620.pdf' pdfpages/mw0620-pArezmazAnam.pdf
cp 'mwcolorpages/MW-main (coloured) 621.pdf' pdfpages/mw0621-pAriNAmika.pdf
cp 'mwcolorpages/MW-main (coloured) 622.pdf' pdfpages/mw0622-pArdAkI.pdf
cp 'mwcolorpages/MW-main (coloured) 623.pdf' pdfpages/mw0623-pAlakagotra.pdf
cp 'mwcolorpages/MW-main (coloured) 624.pdf' pdfpages/mw0624-pAzupatajJAna.pdf
cp 'mwcolorpages/MW-main (coloured) 625.pdf' pdfpages/mw0625-piGgalakANva.pdf
cp 'mwcolorpages/MW-main (coloured) 626.pdf' pdfpages/mw0626-piNDaya.pdf
cp 'mwcolorpages/MW-main (coloured) 627.pdf' pdfpages/mw0627-pitRhU.pdf
cp 'mwcolorpages/MW-main (coloured) 628.pdf' pdfpages/mw0628-pippalAda.pdf
cp 'mwcolorpages/MW-main (coloured) 629.pdf' pdfpages/mw0629-piSTAda.pdf
cp 'mwcolorpages/MW-main (coloured) 63.pdf' pdfpages/mw0063-abhidadhat.pdf
cp 'mwcolorpages/MW-main (coloured) 630.pdf' pdfpages/mw0630-pItavAlukA.pdf
cp 'mwcolorpages/MW-main (coloured) 631.pdf' pdfpages/mw0631-puMdhvaja.pdf
cp 'mwcolorpages/MW-main (coloured) 632.pdf' pdfpages/mw0632-puNDarya.pdf
cp 'mwcolorpages/MW-main (coloured) 633.pdf' pdfpages/mw0633-putraphalabhaktR.pdf
cp 'mwcolorpages/MW-main (coloured) 634.pdf' pdfpages/mw0634-punarmanya.pdf
cp 'mwcolorpages/MW-main (coloured) 635.pdf' pdfpages/mw0635-purAhita.pdf
cp 'mwcolorpages/MW-main (coloured) 636.pdf' pdfpages/mw0636-puraya.pdf
cp 'mwcolorpages/MW-main (coloured) 637.pdf' pdfpages/mw0637-puruha.pdf
cp 'mwcolorpages/MW-main (coloured) 638.pdf' pdfpages/mw0638-purv.pdf
cp 'mwcolorpages/MW-main (coloured) 639.pdf' pdfpages/mw0639-puSkarAkhya.pdf
cp 'mwcolorpages/MW-main (coloured) 64.pdf' pdfpages/mw0064-abhiniHsRp.pdf
cp 'mwcolorpages/MW-main (coloured) 640.pdf' pdfpages/mw0640-puSparasa.pdf
cp 'mwcolorpages/MW-main (coloured) 641.pdf' pdfpages/mw0641-pUtadhAnya.pdf
cp 'mwcolorpages/MW-main (coloured) 642.pdf' pdfpages/mw0642-pUrAmla.pdf
cp 'mwcolorpages/MW-main (coloured) 643.pdf' pdfpages/mw0643-pUruSa.pdf
cp 'mwcolorpages/MW-main (coloured) 644.pdf' pdfpages/mw0644-pUrvabhakSikA.pdf
cp 'mwcolorpages/MW-main (coloured) 645.pdf' pdfpages/mw0645-pUrvodakplava.pdf
cp 'mwcolorpages/MW-main (coloured) 646.pdf' pdfpages/mw0646-pRthakparNI.pdf
cp 'mwcolorpages/MW-main (coloured) 647.pdf' pdfpages/mw0647-pRthukIya.pdf
cp 'mwcolorpages/MW-main (coloured) 648.pdf' pdfpages/mw0648-pRSThayAyin.pdf
cp 'mwcolorpages/MW-main (coloured) 649.pdf' pdfpages/mw0649-peSaNa.pdf
cp 'mwcolorpages/MW-main (coloured) 65.pdf' pdfpages/mw0065-abhipatana.pdf
cp 'mwcolorpages/MW-main (coloured) 650.pdf' pdfpages/mw0650-poJch.pdf
cp 'mwcolorpages/MW-main (coloured) 651.pdf' pdfpages/mw0651-pautika.pdf
cp 'mwcolorpages/MW-main (coloured) 652.pdf' pdfpages/mw0652-paulastya.pdf
cp 'mwcolorpages/MW-main (coloured) 653.pdf' pdfpages/mw0653-prakalyANa.pdf
cp 'mwcolorpages/MW-main (coloured) 654.pdf' pdfpages/mw0654-prakRti.pdf
cp 'mwcolorpages/MW-main (coloured) 655.pdf' pdfpages/mw0655-prakrantR.pdf
cp 'mwcolorpages/MW-main (coloured) 656.pdf' pdfpages/mw0656-pragayaNa.pdf
cp 'mwcolorpages/MW-main (coloured) 657.pdf' pdfpages/mw0657-pracaNDavarman.pdf
cp 'mwcolorpages/MW-main (coloured) 658.pdf' pdfpages/mw0658-pracchAdya.pdf
cp 'mwcolorpages/MW-main (coloured) 659.pdf' pdfpages/mw0659-prajalpana.pdf
cp 'mwcolorpages/MW-main (coloured) 66.pdf' pdfpages/mw0066-abhiprabhU.pdf
cp 'mwcolorpages/MW-main (coloured) 660.pdf' pdfpages/mw0660-praNAla.pdf
cp 'mwcolorpages/MW-main (coloured) 661.pdf' pdfpages/mw0661-praNodya.pdf
cp 'mwcolorpages/MW-main (coloured) 662.pdf' pdfpages/mw0662-pratigAtram.pdf
cp 'mwcolorpages/MW-main (coloured) 663.pdf' pdfpages/mw0663-pratiyuvati.pdf
cp 'mwcolorpages/MW-main (coloured) 664.pdf' pdfpages/mw0664-pratyaGgiras.pdf
cp 'mwcolorpages/MW-main (coloured) 665.pdf' pdfpages/mw0665-pratikSepaNa.pdf
cp 'mwcolorpages/MW-main (coloured) 666.pdf' pdfpages/mw0666-pratijJAti.pdf
cp 'mwcolorpages/MW-main (coloured) 667.pdf' pdfpages/mw0667-pratinyas.pdf
cp 'mwcolorpages/MW-main (coloured) 668.pdf' pdfpages/mw0668-pratiprayAta.pdf
cp 'mwcolorpages/MW-main (coloured) 669.pdf' pdfpages/mw0669-pratimaNDita.pdf
cp 'mwcolorpages/MW-main (coloured) 67.pdf' pdfpages/mw0067-abhibhavana.pdf
cp 'mwcolorpages/MW-main (coloured) 670.pdf' pdfpages/mw0670-pratilamb.pdf
cp 'mwcolorpages/MW-main (coloured) 671.pdf' pdfpages/mw0671-pratizrama.pdf
cp 'mwcolorpages/MW-main (coloured) 672.pdf' pdfpages/mw0672-pratisaMvad.pdf
cp 'mwcolorpages/MW-main (coloured) 673.pdf' pdfpages/mw0673-pratisvana.pdf
cp 'mwcolorpages/MW-main (coloured) 674.pdf' pdfpages/mw0674-pratikSita.pdf
cp 'mwcolorpages/MW-main (coloured) 675.pdf' pdfpages/mw0675-pratIka.pdf
cp 'mwcolorpages/MW-main (coloured) 676.pdf' pdfpages/mw0676-pratyard.pdf
cp 'mwcolorpages/MW-main (coloured) 677.pdf' pdfpages/mw0677-pratyApatti.pdf
cp 'mwcolorpages/MW-main (coloured) 678.pdf' pdfpages/mw0678-pratyuddIp.pdf
cp 'mwcolorpages/MW-main (coloured) 679.pdf' pdfpages/mw0679-prathamakathita.pdf
cp 'mwcolorpages/MW-main (coloured) 68.pdf' pdfpages/mw0068-abhiyAcJA.pdf
cp 'mwcolorpages/MW-main (coloured) 680.pdf' pdfpages/mw0680-pradeza.pdf
cp 'mwcolorpages/MW-main (coloured) 681.pdf' pdfpages/mw0681-pradhAnatva.pdf
cp 'mwcolorpages/MW-main (coloured) 682.pdf' pdfpages/mw0682-prapat.pdf
cp 'mwcolorpages/MW-main (coloured) 683.pdf' pdfpages/mw0683-prapyAyana.pdf
cp 'mwcolorpages/MW-main (coloured) 684.pdf' pdfpages/mw0684-prabhAkITa.pdf
cp 'mwcolorpages/MW-main (coloured) 685.pdf' pdfpages/mw0685-prabhartavya.pdf
cp 'mwcolorpages/MW-main (coloured) 686.pdf' pdfpages/mw0686-pramANatas.pdf
cp 'mwcolorpages/MW-main (coloured) 687.pdf' pdfpages/mw0687-pramodam.pdf
cp 'mwcolorpages/MW-main (coloured) 688.pdf' pdfpages/mw0688-prayAsita.pdf
cp 'mwcolorpages/MW-main (coloured) 689.pdf' pdfpages/mw0689-prayudh.pdf
cp 'mwcolorpages/MW-main (coloured) 69.pdf' pdfpages/mw0069-abhivAdana.pdf
cp 'mwcolorpages/MW-main (coloured) 690.pdf' pdfpages/mw0690-pralayana.pdf
cp 'mwcolorpages/MW-main (coloured) 691.pdf' pdfpages/mw0691-pravarasena.pdf
cp 'mwcolorpages/MW-main (coloured) 692.pdf' pdfpages/mw0692-pravicint.pdf
cp 'mwcolorpages/MW-main (coloured) 693.pdf' pdfpages/mw0693-praveSTavya.pdf
cp 'mwcolorpages/MW-main (coloured) 694.pdf' pdfpages/mw0694-pravRttaka.pdf
cp 'mwcolorpages/MW-main (coloured) 695.pdf' pdfpages/mw0695-prazaMsita.pdf
cp 'mwcolorpages/MW-main (coloured) 696.pdf' pdfpages/mw0696-praznaya.pdf
cp 'mwcolorpages/MW-main (coloured) 697.pdf' pdfpages/mw0697-prasAdaka.pdf
cp 'mwcolorpages/MW-main (coloured) 698.pdf' pdfpages/mw0698-prasup.pdf
cp 'mwcolorpages/MW-main (coloured) 699.pdf' pdfpages/mw0699-praskaNva.pdf
cp 'mwcolorpages/MW-main (coloured) 7.pdf' pdfpages/mw0007-aghamAra.pdf
cp 'mwcolorpages/MW-main (coloured) 70.pdf' pdfpages/mw0070-abhivIra.pdf
cp 'mwcolorpages/MW-main (coloured) 700.pdf' pdfpages/mw0700-prasnu.pdf
cp 'mwcolorpages/MW-main (coloured) 701.pdf' pdfpages/mw0701-prahAyya.pdf
cp 'mwcolorpages/MW-main (coloured) 702.pdf' pdfpages/mw0702-prAkRta.pdf
cp 'mwcolorpages/MW-main (coloured) 703.pdf' pdfpages/mw0703-prAMzutA.pdf
cp 'mwcolorpages/MW-main (coloured) 704.pdf' pdfpages/mw0704-prAkkUla.pdf
cp 'mwcolorpages/MW-main (coloured) 705.pdf' pdfpages/mw0705-prAcInAtAna.pdf
cp 'mwcolorpages/MW-main (coloured) 706.pdf' pdfpages/mw0706-prANAtyaya.pdf
cp 'mwcolorpages/MW-main (coloured) 707.pdf' pdfpages/mw0707-prAtIpa.pdf
cp 'mwcolorpages/MW-main (coloured) 708.pdf' pdfpages/mw0708-prApya.pdf
cp 'mwcolorpages/MW-main (coloured) 709.pdf' pdfpages/mw0709-prArh.pdf
cp 'mwcolorpages/MW-main (coloured) 71.pdf' pdfpages/mw0071-abhizriS.pdf
cp 'mwcolorpages/MW-main (coloured) 710.pdf' pdfpages/mw0710-priya.pdf
cp 'mwcolorpages/MW-main (coloured) 711.pdf' pdfpages/mw0711-priyaGgu.pdf
cp 'mwcolorpages/MW-main (coloured) 712.pdf' pdfpages/mw0712-pretacArin.pdf
cp 'mwcolorpages/MW-main (coloured) 713.pdf' pdfpages/mw0713-praiSa.pdf
cp 'mwcolorpages/MW-main (coloured) 714.pdf' pdfpages/mw0714-prodgrIvam.pdf
cp 'mwcolorpages/MW-main (coloured) 715.pdf' pdfpages/mw0715-plakSasamudbhavA.pdf
cp 'mwcolorpages/MW-main (coloured) 716.pdf' pdfpages/mw0716-phakka.pdf
cp 'mwcolorpages/MW-main (coloured) 717.pdf' pdfpages/mw0717-phalaprajanana.pdf
cp 'mwcolorpages/MW-main (coloured) 718.pdf' pdfpages/mw0718-phullatubarI.pdf
cp 'mwcolorpages/MW-main (coloured) 719.pdf' pdfpages/mw0719-phenAgra.pdf
cp 'mwcolorpages/MW-main (coloured) 72.pdf' pdfpages/mw0072-abhiSvaGga.pdf
cp 'mwcolorpages/MW-main (coloured) 720.pdf' pdfpages/mw0720-baddhR.pdf
cp 'mwcolorpages/MW-main (coloured) 721.pdf' pdfpages/mw0721-bandhanRtya.pdf
cp 'mwcolorpages/MW-main (coloured) 722.pdf' pdfpages/mw0722-barAsI.pdf
cp 'mwcolorpages/MW-main (coloured) 723.pdf' pdfpages/mw0723-balabalI.pdf
cp 'mwcolorpages/MW-main (coloured) 724.pdf' pdfpages/mw0724-balidviS.pdf
cp 'mwcolorpages/MW-main (coloured) 725.pdf' pdfpages/mw0725-bahutRSNa.pdf
cp 'mwcolorpages/MW-main (coloured) 726.pdf' pdfpages/mw0726-bahuvyaya.pdf
cp 'mwcolorpages/MW-main (coloured) 727.pdf' pdfpages/mw0727-bahirdhvajA.pdf
cp 'mwcolorpages/MW-main (coloured) 728.pdf' pdfpages/mw0728-bAdha.pdf
cp 'mwcolorpages/MW-main (coloured) 729.pdf' pdfpages/mw0729-bAlagopAla.pdf
cp 'mwcolorpages/MW-main (coloured) 73.pdf' pdfpages/mw0073-abhisaMnaddha.pdf
cp 'mwcolorpages/MW-main (coloured) 730.pdf' pdfpages/mw0730-bASkalazAkhA.pdf
cp 'mwcolorpages/MW-main (coloured) 731.pdf' pdfpages/mw0731-bAhyakakSa.pdf
cp 'mwcolorpages/MW-main (coloured) 732.pdf' pdfpages/mw0732-birAla.pdf
cp 'mwcolorpages/MW-main (coloured) 733.pdf' pdfpages/mw0733-bIjya.pdf
cp 'mwcolorpages/MW-main (coloured) 734.pdf' pdfpages/mw0734-buddhipUrvaka.pdf
cp 'mwcolorpages/MW-main (coloured) 735.pdf' pdfpages/mw0735-bodheya.pdf
cp 'mwcolorpages/MW-main (coloured) 736.pdf' pdfpages/mw0736-bRhatkathA.pdf
cp 'mwcolorpages/MW-main (coloured) 737.pdf' pdfpages/mw0737-bRhannAyakIdaNDaka.pdf
cp 'mwcolorpages/MW-main (coloured) 738.pdf' pdfpages/mw0738-brahma.pdf
cp 'mwcolorpages/MW-main (coloured) 739.pdf' pdfpages/mw0739-brahmadeva.pdf
cp 'mwcolorpages/MW-main (coloured) 74.pdf' pdfpages/mw0074-abhiskandam.pdf
cp 'mwcolorpages/MW-main (coloured) 740.pdf' pdfpages/mw0740-brahmavAdya.pdf
cp 'mwcolorpages/MW-main (coloured) 741.pdf' pdfpages/mw0741-brahmodumbara.pdf
cp 'mwcolorpages/MW-main (coloured) 742.pdf' pdfpages/mw0742-brAhmaNi.pdf
cp 'mwcolorpages/MW-main (coloured) 743.pdf' pdfpages/mw0743-bhaj.pdf
cp 'mwcolorpages/MW-main (coloured) 744.pdf' pdfpages/mw0744-bhagavatsvatantratA.pdf
cp 'mwcolorpages/MW-main (coloured) 745.pdf' pdfpages/mw0745-bhaGguranizcaya.pdf
cp 'mwcolorpages/MW-main (coloured) 746.pdf' pdfpages/mw0746-bhadrakaNTa.pdf
cp 'mwcolorpages/MW-main (coloured) 747.pdf' pdfpages/mw0747-bhandhuka.pdf
cp 'mwcolorpages/MW-main (coloured) 748.pdf' pdfpages/mw0748-bhariman.pdf
cp 'mwcolorpages/MW-main (coloured) 749.pdf' pdfpages/mw0749-bhavakalpa.pdf
cp 'mwcolorpages/MW-main (coloured) 75.pdf' pdfpages/mw0075-abhISTi.pdf
cp 'mwcolorpages/MW-main (coloured) 750.pdf' pdfpages/mw0750-bhaviSyottara.pdf
cp 'mwcolorpages/MW-main (coloured) 751.pdf' pdfpages/mw0751-bhAtu.pdf
cp 'mwcolorpages/MW-main (coloured) 752.pdf' pdfpages/mw0752-bhAgya.pdf
cp 'mwcolorpages/MW-main (coloured) 753.pdf' pdfpages/mw0753-bhAma.pdf
cp 'mwcolorpages/MW-main (coloured) 754.pdf' pdfpages/mw0754-bhArman.pdf
cp 'mwcolorpages/MW-main (coloured) 755.pdf' pdfpages/mw0755-bhAvodaya.pdf
cp 'mwcolorpages/MW-main (coloured) 756.pdf' pdfpages/mw0756-bhAs.pdf
cp 'mwcolorpages/MW-main (coloured) 757.pdf' pdfpages/mw0757-bhitta.pdf
cp 'mwcolorpages/MW-main (coloured) 758.pdf' pdfpages/mw0758-bhihu.pdf
cp 'mwcolorpages/MW-main (coloured) 759.pdf' pdfpages/mw0759-bhIra.pdf
cp 'mwcolorpages/MW-main (coloured) 76.pdf' pdfpages/mw0076-abhyapazri.pdf
cp 'mwcolorpages/MW-main (coloured) 760.pdf' pdfpages/mw0760-bhuJjApaya.pdf
cp 'mwcolorpages/MW-main (coloured) 761.pdf' pdfpages/mw0761-bhUkadamba.pdf
cp 'mwcolorpages/MW-main (coloured) 762.pdf' pdfpages/mw0762-bhUtaghna.pdf
cp 'mwcolorpages/MW-main (coloured) 763.pdf' pdfpages/mw0763-bhUtiziva.pdf
cp 'mwcolorpages/MW-main (coloured) 764.pdf' pdfpages/mw0764-bhUri.pdf
cp 'mwcolorpages/MW-main (coloured) 765.pdf' pdfpages/mw0765-bhRtyakAmakRt.pdf
cp 'mwcolorpages/MW-main (coloured) 766.pdf' pdfpages/mw0766-bhRzatA.pdf
cp 'mwcolorpages/MW-main (coloured) 767.pdf' pdfpages/mw0767-bhaikSuka.pdf
cp 'mwcolorpages/MW-main (coloured) 768.pdf' pdfpages/mw0768-bhojakaTIya.pdf
cp 'mwcolorpages/MW-main (coloured) 769.pdf' pdfpages/mw0769-bhauvAyana.pdf
cp 'mwcolorpages/MW-main (coloured) 77.pdf' pdfpages/mw0077-abhyAsatA.pdf
cp 'mwcolorpages/MW-main (coloured) 770.pdf' pdfpages/mw0770-bhrami.pdf
cp 'mwcolorpages/MW-main (coloured) 771.pdf' pdfpages/mw0771-bhRkuTi.pdf
cp 'mwcolorpages/MW-main (coloured) 772.pdf' pdfpages/mw0772-makSikAmala.pdf
cp 'mwcolorpages/MW-main (coloured) 773.pdf' pdfpages/mw0773-maGgalavAra.pdf
cp 'mwcolorpages/MW-main (coloured) 774.pdf' pdfpages/mw0774-maJjarikA.pdf
cp 'mwcolorpages/MW-main (coloured) 775.pdf' pdfpages/mw0775-maNidhAriNI.pdf
cp 'mwcolorpages/MW-main (coloured) 776.pdf' pdfpages/mw0776-maNDalatva.pdf
cp 'mwcolorpages/MW-main (coloured) 777.pdf' pdfpages/mw0777-matsyezvaratIrtha.pdf
cp 'mwcolorpages/MW-main (coloured) 778.pdf' pdfpages/mw0778-madakAraNa.pdf
cp 'mwcolorpages/MW-main (coloured) 779.pdf' pdfpages/mw0779-madirAmadAndha.pdf
cp 'mwcolorpages/MW-main (coloured) 78.pdf' pdfpages/mw0078-abhyAsAdana.pdf
cp 'mwcolorpages/MW-main (coloured) 780.pdf' pdfpages/mw0780-madhunADI.pdf
cp 'mwcolorpages/MW-main (coloured) 781.pdf' pdfpages/mw0781-madhUtthita.pdf
cp 'mwcolorpages/MW-main (coloured) 782.pdf' pdfpages/mw0782-madhyapatita.pdf
cp 'mwcolorpages/MW-main (coloured) 783.pdf' pdfpages/mw0783-madhvamAhAtmya.pdf
cp 'mwcolorpages/MW-main (coloured) 784.pdf' pdfpages/mw0784-manaskAnta.pdf
cp 'mwcolorpages/MW-main (coloured) 785.pdf' pdfpages/mw0785-manuSyaviz.pdf
cp 'mwcolorpages/MW-main (coloured) 786.pdf' pdfpages/mw0786-mantrakamalAkara.pdf
cp 'mwcolorpages/MW-main (coloured) 787.pdf' pdfpages/mw0787-manvarthacandrikA.pdf
cp 'mwcolorpages/MW-main (coloured) 788.pdf' pdfpages/mw0788-mandakarNi.pdf
cp 'mwcolorpages/MW-main (coloured) 789.pdf' pdfpages/mw0789-manmathin.pdf
cp 'mwcolorpages/MW-main (coloured) 79.pdf' pdfpages/mw0079-abhyupanivRt.pdf
cp 'mwcolorpages/MW-main (coloured) 790.pdf' pdfpages/mw0790-marAlagamanA.pdf
cp 'mwcolorpages/MW-main (coloured) 791.pdf' pdfpages/mw0791-maroli.pdf
cp 'mwcolorpages/MW-main (coloured) 792.pdf' pdfpages/mw0792-marv.pdf
cp 'mwcolorpages/MW-main (coloured) 793.pdf' pdfpages/mw0793-malli.pdf
cp 'mwcolorpages/MW-main (coloured) 794.pdf' pdfpages/mw0794-masAragalvarkamaya.pdf
cp 'mwcolorpages/MW-main (coloured) 795.pdf' pdfpages/mw0795-mahAkaraJja.pdf
cp 'mwcolorpages/MW-main (coloured) 796.pdf' pdfpages/mw0796-mahAjAti.pdf
cp 'mwcolorpages/MW-main (coloured) 797.pdf' pdfpages/mw0797-mahAnAnAtva.pdf
cp 'mwcolorpages/MW-main (coloured) 798.pdf' pdfpages/mw0798-mahApheTkArIya.pdf
cp 'mwcolorpages/MW-main (coloured) 799.pdf' pdfpages/mw0799-mahAmAyUra.pdf
cp 'mwcolorpages/MW-main (coloured) 8.pdf' pdfpages/mw0008-aGgAdhipa.pdf
cp 'mwcolorpages/MW-main (coloured) 80.pdf' pdfpages/mw0080-abhreSa.pdf
cp 'mwcolorpages/MW-main (coloured) 800.pdf' pdfpages/mw0800-mahArcis.pdf
cp 'mwcolorpages/MW-main (coloured) 801.pdf' pdfpages/mw0801-mahAvrAta.pdf
cp 'mwcolorpages/MW-main (coloured) 802.pdf' pdfpages/mw0802-mahAsaura.pdf
cp 'mwcolorpages/MW-main (coloured) 803.pdf' pdfpages/mw0803-mahiSvani.pdf
cp 'mwcolorpages/MW-main (coloured) 804.pdf' pdfpages/mw0804-mahiSa.pdf
cp 'mwcolorpages/MW-main (coloured) 805.pdf' pdfpages/mw0805-mAMzcatva.pdf
cp 'mwcolorpages/MW-main (coloured) 806.pdf' pdfpages/mw0806-mAghavatacApa.pdf
cp 'mwcolorpages/MW-main (coloured) 807.pdf' pdfpages/mw0807-mAtalisArathi.pdf
cp 'mwcolorpages/MW-main (coloured) 808.pdf' pdfpages/mw0808-mAtputra.pdf
cp 'mwcolorpages/MW-main (coloured) 809.pdf' pdfpages/mw0809-mAdhurya.pdf
cp 'mwcolorpages/MW-main (coloured) 81.pdf' pdfpages/mw0081-amardita.pdf
cp 'mwcolorpages/MW-main (coloured) 810.pdf' pdfpages/mw0810-mAnavakalpasUtra.pdf
cp 'mwcolorpages/MW-main (coloured) 811.pdf' pdfpages/mw0811-mAmalladevI.pdf
cp 'mwcolorpages/MW-main (coloured) 812.pdf' pdfpages/mw0812-mArI.pdf
cp 'mwcolorpages/MW-main (coloured) 813.pdf' pdfpages/mw0813-mArjaka.pdf
cp 'mwcolorpages/MW-main (coloured) 814.pdf' pdfpages/mw0814-mAlinItantra.pdf
cp 'mwcolorpages/MW-main (coloured) 815.pdf' pdfpages/mw0815-mAsAnumAsika.pdf
cp 'mwcolorpages/MW-main (coloured) 816.pdf' pdfpages/mw0816-mitadakSiNa.pdf
cp 'mwcolorpages/MW-main (coloured) 817.pdf' pdfpages/mw0817-mithunabhAva.pdf
cp 'mwcolorpages/MW-main (coloured) 818.pdf' pdfpages/mw0818-mizrakezava.pdf
cp 'mwcolorpages/MW-main (coloured) 819.pdf' pdfpages/mw0819-mImAMsAbhASya.pdf
cp 'mwcolorpages/MW-main (coloured) 82.pdf' pdfpages/mw0082-amiSa.pdf
cp 'mwcolorpages/MW-main (coloured) 820.pdf' pdfpages/mw0820-mukhaphullaka.pdf
cp 'mwcolorpages/MW-main (coloured) 821.pdf' pdfpages/mw0821-muktakeza.pdf
cp 'mwcolorpages/MW-main (coloured) 822.pdf' pdfpages/mw0822-muTTa.pdf
cp 'mwcolorpages/MW-main (coloured) 823.pdf' pdfpages/mw0823-mudhA.pdf
cp 'mwcolorpages/MW-main (coloured) 824.pdf' pdfpages/mw0824-mUrchAvat.pdf
cp 'mwcolorpages/MW-main (coloured) 825.pdf' pdfpages/mw0825-mugdha.pdf
cp 'mwcolorpages/MW-main (coloured) 826.pdf' pdfpages/mw0826-mUtraukasAda.pdf
cp 'mwcolorpages/MW-main (coloured) 827.pdf' pdfpages/mw0827-mUlasthAyin.pdf
cp 'mwcolorpages/MW-main (coloured) 828.pdf' pdfpages/mw0828-mRtyukanyA.pdf
cp 'mwcolorpages/MW-main (coloured) 829.pdf' pdfpages/mw0829-mRgazIrSan.pdf
cp 'mwcolorpages/MW-main (coloured) 83.pdf' pdfpages/mw0083-amedhas.pdf
cp 'mwcolorpages/MW-main (coloured) 830.pdf' pdfpages/mw0830-mRNAlakaNTha.pdf
cp 'mwcolorpages/MW-main (coloured) 831.pdf' pdfpages/mw0831-mRdhra.pdf
cp 'mwcolorpages/MW-main (coloured) 832.pdf' pdfpages/mw0832-megharaga.pdf
cp 'mwcolorpages/MW-main (coloured) 833.pdf' pdfpages/mw0833-medhaja.pdf
cp 'mwcolorpages/MW-main (coloured) 834.pdf' pdfpages/mw0834-meSUraNa.pdf
cp 'mwcolorpages/MW-main (coloured) 835.pdf' pdfpages/mw0835-mumokSayiSu.pdf
cp 'mwcolorpages/MW-main (coloured) 836.pdf' pdfpages/mw0836-morAkabhavana.pdf
cp 'mwcolorpages/MW-main (coloured) 837.pdf' pdfpages/mw0837-maunagopAla.pdf
cp 'mwcolorpages/MW-main (coloured) 838.pdf' pdfpages/mw0838-mlecchAkhya.pdf
cp 'mwcolorpages/MW-main (coloured) 839.pdf' pdfpages/mw0839-yaj.pdf
cp 'mwcolorpages/MW-main (coloured) 84.pdf' pdfpages/mw0084-ambuzirISikA.pdf
cp 'mwcolorpages/MW-main (coloured) 840.pdf' pdfpages/mw0840-yajJabhAjana.pdf
cp 'mwcolorpages/MW-main (coloured) 841.pdf' pdfpages/mw0841-yatana.pdf
cp 'mwcolorpages/MW-main (coloured) 842.pdf' pdfpages/mw0842-yathAgamanam.pdf
cp 'mwcolorpages/MW-main (coloured) 843.pdf' pdfpages/mw0843-yathArUpa.pdf
cp 'mwcolorpages/MW-main (coloured) 844.pdf' pdfpages/mw0844-yathocita.pdf
cp 'mwcolorpages/MW-main (coloured) 845.pdf' pdfpages/mw0845-yadIya.pdf
cp 'mwcolorpages/MW-main (coloured) 846.pdf' pdfpages/mw0846-yantrasaMgraha.pdf
cp 'mwcolorpages/MW-main (coloured) 847.pdf' pdfpages/mw0847-yamalacchada.pdf
cp 'mwcolorpages/MW-main (coloured) 848.pdf' pdfpages/mw0848-yavya.pdf
cp 'mwcolorpages/MW-main (coloured) 849.pdf' pdfpages/mw0849-yaSTika.pdf
cp 'mwcolorpages/MW-main (coloured) 85.pdf' pdfpages/mw0085-ayavaka.pdf
cp 'mwcolorpages/MW-main (coloured) 850.pdf' pdfpages/mw0850-yApya.pdf
cp 'mwcolorpages/MW-main (coloured) 851.pdf' pdfpages/mw0851-yAjya.pdf
cp 'mwcolorpages/MW-main (coloured) 852.pdf' pdfpages/mw0852-yAmuneSTaka.pdf
cp 'mwcolorpages/MW-main (coloured) 853.pdf' pdfpages/mw0853-yAvana.pdf
cp 'mwcolorpages/MW-main (coloured) 854.pdf' pdfpages/mw0854-yuktikathana.pdf
cp 'mwcolorpages/MW-main (coloured) 855.pdf' pdfpages/mw0855-yuddhakANDa.pdf
cp 'mwcolorpages/MW-main (coloured) 856.pdf' pdfpages/mw0856-yuSmota.pdf
cp 'mwcolorpages/MW-main (coloured) 857.pdf' pdfpages/mw0857-yogatantra.pdf
cp 'mwcolorpages/MW-main (coloured) 858.pdf' pdfpages/mw0858-yoginI.pdf
cp 'mwcolorpages/MW-main (coloured) 859.pdf' pdfpages/mw0859-yauktAzva.pdf
cp 'mwcolorpages/MW-main (coloured) 86.pdf' pdfpages/mw0086-ayogyatA.pdf
cp 'mwcolorpages/MW-main (coloured) 860.pdf' pdfpages/mw0860-rakSaNArtham.pdf
cp 'mwcolorpages/MW-main (coloured) 861.pdf' pdfpages/mw0861-racayitR.pdf
cp 'mwcolorpages/MW-main (coloured) 862.pdf' pdfpages/mw0862-raktaphala.pdf
cp 'mwcolorpages/MW-main (coloured) 863.pdf' pdfpages/mw0863-raja.pdf
cp 'mwcolorpages/MW-main (coloured) 864.pdf' pdfpages/mw0864-raNapakSin.pdf
cp 'mwcolorpages/MW-main (coloured) 865.pdf' pdfpages/mw0865-ratnarekhA.pdf
cp 'mwcolorpages/MW-main (coloured) 866.pdf' pdfpages/mw0866-rathasArathi.pdf
cp 'mwcolorpages/MW-main (coloured) 867.pdf' pdfpages/mw0867-randhrAnusArin.pdf
cp 'mwcolorpages/MW-main (coloured) 868.pdf' pdfpages/mw0868-ratisundara.pdf
cp 'mwcolorpages/MW-main (coloured) 869.pdf' pdfpages/mw0869-ravaNaka.pdf
cp 'mwcolorpages/MW-main (coloured) 87.pdf' pdfpages/mw0087-aratni.pdf
cp 'mwcolorpages/MW-main (coloured) 870.pdf' pdfpages/mw0870-rasatattvasAra.pdf
cp 'mwcolorpages/MW-main (coloured) 871.pdf' pdfpages/mw0871-rasApuS.pdf
cp 'mwcolorpages/MW-main (coloured) 872.pdf' pdfpages/mw0872-rAkSoghna.pdf
cp 'mwcolorpages/MW-main (coloured) 873.pdf' pdfpages/mw0873-rAjakaustubha.pdf
cp 'mwcolorpages/MW-main (coloured) 874.pdf' pdfpages/mw0874-nAtharANaka.pdf
cp 'mwcolorpages/MW-main (coloured) 875.pdf' pdfpages/mw0875-rAjanvat.pdf
cp 'mwcolorpages/MW-main (coloured) 876.pdf' pdfpages/mw0876-rAtna.pdf
cp 'mwcolorpages/MW-main (coloured) 877.pdf' pdfpages/mw0877-rAndrya.pdf
cp 'mwcolorpages/MW-main (coloured) 878.pdf' pdfpages/mw0878-rAmavarNanastotra.pdf
cp 'mwcolorpages/MW-main (coloured) 879.pdf' pdfpages/mw0879-rAla.pdf
cp 'mwcolorpages/MW-main (coloured) 88.pdf' pdfpages/mw0088-arikta.pdf
cp 'mwcolorpages/MW-main (coloured) 880.pdf' pdfpages/mw0880-rAhukanya.pdf
cp 'mwcolorpages/MW-main (coloured) 881.pdf' pdfpages/mw0881-rebhasUnu.pdf
cp 'mwcolorpages/MW-main (coloured) 882.pdf' pdfpages/mw0882-ruk.pdf
cp 'mwcolorpages/MW-main (coloured) 883.pdf' pdfpages/mw0883-ruNaskarA.pdf
cp 'mwcolorpages/MW-main (coloured) 884.pdf' pdfpages/mw0884-rudrAnuSThAnapaddhati.pdf
cp 'mwcolorpages/MW-main (coloured) 885.pdf' pdfpages/mw0885-rurukSaNi.pdf
cp 'mwcolorpages/MW-main (coloured) 886.pdf' pdfpages/mw0886-rUpakartR.pdf
cp 'mwcolorpages/MW-main (coloured) 887.pdf' pdfpages/mw0887-re.pdf
cp 'mwcolorpages/MW-main (coloured) 888.pdf' pdfpages/mw0888-revatottara.pdf
cp 'mwcolorpages/MW-main (coloured) 889.pdf' pdfpages/mw0889-rocanaphala.pdf
cp 'mwcolorpages/MW-main (coloured) 89.pdf' pdfpages/mw0089-arUpajJa.pdf
cp 'mwcolorpages/MW-main (coloured) 890.pdf' pdfpages/mw0890-romAzrayaphalA.pdf
cp 'mwcolorpages/MW-main (coloured) 891.pdf' pdfpages/mw0891-rauT.pdf
cp 'mwcolorpages/MW-main (coloured) 892.pdf' pdfpages/mw0892-lakSabhUta.pdf
cp 'mwcolorpages/MW-main (coloured) 893.pdf' pdfpages/mw0893-lakSmIMdadA.pdf
cp 'mwcolorpages/MW-main (coloured) 894.pdf' pdfpages/mw0894-laghukaGkola.pdf
cp 'mwcolorpages/MW-main (coloured) 895.pdf' pdfpages/mw0895-laGkAri.pdf
cp 'mwcolorpages/MW-main (coloured) 896.pdf' pdfpages/mw0896-latAkaraJja.pdf
cp 'mwcolorpages/MW-main (coloured) 897.pdf' pdfpages/mw0897-lambhitalobha.pdf
cp 'mwcolorpages/MW-main (coloured) 898.pdf' pdfpages/mw0898-lalitAkramadIpikA.pdf
cp 'mwcolorpages/MW-main (coloured) 899.pdf' pdfpages/mw0899-lavaNAnbataka.pdf
cp 'mwcolorpages/MW-main (coloured) 9.pdf' pdfpages/mw0009-acintita.pdf
cp 'mwcolorpages/MW-main (coloured) 90.pdf' pdfpages/mw0090-arcatri.pdf
cp 'mwcolorpages/MW-main (coloured) 900.pdf' pdfpages/mw0900-lAGkAyana.pdf
cp 'mwcolorpages/MW-main (coloured) 901.pdf' pdfpages/mw0901-lAvaNaka.pdf
cp 'mwcolorpages/MW-main (coloured) 902.pdf' pdfpages/mw0902-liGgakAraNavAda.pdf
cp 'mwcolorpages/MW-main (coloured) 903.pdf' pdfpages/mw0903-libi.pdf
cp 'mwcolorpages/MW-main (coloured) 904.pdf' pdfpages/mw0904-lugi.pdf
cp 'mwcolorpages/MW-main (coloured) 905.pdf' pdfpages/mw0905-lubdhajana.pdf
cp 'mwcolorpages/MW-main (coloured) 906.pdf' pdfpages/mw0906-leya.pdf
cp 'mwcolorpages/MW-main (coloured) 907.pdf' pdfpages/mw0907-lokayAtrA.pdf
cp 'mwcolorpages/MW-main (coloured) 908.pdf' pdfpages/mw0908-loTya.pdf
cp 'mwcolorpages/MW-main (coloured) 909.pdf' pdfpages/mw0909-lohastha.pdf
cp 'mwcolorpages/MW-main (coloured) 91.pdf' pdfpages/mw0091-arthanirvRtti.pdf
cp 'mwcolorpages/MW-main (coloured) 910.pdf' pdfpages/mw0910-lauhAyana.pdf
cp 'mwcolorpages/MW-main (coloured) 911.pdf' pdfpages/mw0911-vakrakaNTa.pdf
cp 'mwcolorpages/MW-main (coloured) 912.pdf' pdfpages/mw0912-vaGkharabhaNDIratha.pdf
cp 'mwcolorpages/MW-main (coloured) 913.pdf' pdfpages/mw0913-vacasya.pdf
cp 'mwcolorpages/MW-main (coloured) 914.pdf' pdfpages/mw0914-vajrazrI.pdf
cp 'mwcolorpages/MW-main (coloured) 915.pdf' pdfpages/mw0915-vaTku.pdf
cp 'mwcolorpages/MW-main (coloured) 916.pdf' pdfpages/mw0916-vatsarAjya.pdf
cp 'mwcolorpages/MW-main (coloured) 917.pdf' pdfpages/mw0917-vadhyaghAtaka.pdf
cp 'mwcolorpages/MW-main (coloured) 918.pdf' pdfpages/mw0918-vanamAtaMga.pdf
cp 'mwcolorpages/MW-main (coloured) 919.pdf' pdfpages/mw0919-vanezaya.pdf
cp 'mwcolorpages/MW-main (coloured) 92.pdf' pdfpages/mw0092-ardhakarNa.pdf
cp 'mwcolorpages/MW-main (coloured) 920.pdf' pdfpages/mw0920-vapuHsrava.pdf
cp 'mwcolorpages/MW-main (coloured) 921.pdf' pdfpages/mw0921-vayodheya.pdf
cp 'mwcolorpages/MW-main (coloured) 922.pdf' pdfpages/mw0922-varUthin.pdf
cp 'mwcolorpages/MW-main (coloured) 923.pdf' pdfpages/mw0923-varAli.pdf
cp 'mwcolorpages/MW-main (coloured) 924.pdf' pdfpages/mw0924-vargakarman.pdf
cp 'mwcolorpages/MW-main (coloured) 925.pdf' pdfpages/mw0925-varNasaMhAra.pdf
cp 'mwcolorpages/MW-main (coloured) 926.pdf' pdfpages/mw0926-vartarUka.pdf
cp 'mwcolorpages/MW-main (coloured) 927.pdf' pdfpages/mw0927-varSadhara.pdf
cp 'mwcolorpages/MW-main (coloured) 928.pdf' pdfpages/mw0928-valayin.pdf
cp 'mwcolorpages/MW-main (coloured) 929.pdf' pdfpages/mw0929-vallikaNTakArikA.pdf
cp 'mwcolorpages/MW-main (coloured) 93.pdf' pdfpages/mw0093-arpitopta.pdf
cp 'mwcolorpages/MW-main (coloured) 930.pdf' pdfpages/mw0930-vazcika.pdf
cp 'mwcolorpages/MW-main (coloured) 931.pdf' pdfpages/mw0931-vasukarNa.pdf
cp 'mwcolorpages/MW-main (coloured) 932.pdf' pdfpages/mw0932-vasyas.pdf
cp 'mwcolorpages/MW-main (coloured) 933.pdf' pdfpages/mw0933-vastuvat.pdf
cp 'mwcolorpages/MW-main (coloured) 934.pdf' pdfpages/mw0934-vahnikanyA.pdf
cp 'mwcolorpages/MW-main (coloured) 935.pdf' pdfpages/mw0935-vAtavat.pdf
cp 'mwcolorpages/MW-main (coloured) 936.pdf' pdfpages/mw0936-vAGga.pdf
cp 'mwcolorpages/MW-main (coloured) 937.pdf' pdfpages/mw0937-vAgdevatA.pdf
cp 'mwcolorpages/MW-main (coloured) 938.pdf' pdfpages/mw0938-vAcyAya.pdf
cp 'mwcolorpages/MW-main (coloured) 939.pdf' pdfpages/mw0939-vAJchaka.pdf
cp 'mwcolorpages/MW-main (coloured) 94.pdf' pdfpages/mw0094-alaka.pdf
cp 'mwcolorpages/MW-main (coloured) 940.pdf' pdfpages/mw0940-vAdakathA.pdf
cp 'mwcolorpages/MW-main (coloured) 941.pdf' pdfpages/mw0941-vAnIra.pdf
cp 'mwcolorpages/MW-main (coloured) 942.pdf' pdfpages/mw0942-vAmanakArikA.pdf
cp 'mwcolorpages/MW-main (coloured) 943.pdf' pdfpages/mw0943-vAyusambhava.pdf
cp 'mwcolorpages/MW-main (coloured) 944.pdf' pdfpages/mw0944-vAravANi.pdf
cp 'mwcolorpages/MW-main (coloured) 945.pdf' pdfpages/mw0945-vArkAruNIputra.pdf
cp 'mwcolorpages/MW-main (coloured) 946.pdf' pdfpages/mw0946-vArSikaprazna.pdf
cp 'mwcolorpages/MW-main (coloured) 947.pdf' pdfpages/mw0947-vAvadUka.pdf
cp 'mwcolorpages/MW-main (coloured) 948.pdf' pdfpages/mw0948-vAsantaka.pdf
cp 'mwcolorpages/MW-main (coloured) 949.pdf' pdfpages/mw0949-vAstuvidhAna.pdf
cp 'mwcolorpages/MW-main (coloured) 95.pdf' pdfpages/mw0095-alAbha.pdf
cp 'mwcolorpages/MW-main (coloured) 950.pdf' pdfpages/mw0950-vikapAla.pdf
cp 'mwcolorpages/MW-main (coloured) 951.pdf' pdfpages/mw0951-videza.pdf
cp 'mwcolorpages/MW-main (coloured) 952.pdf' pdfpages/mw0952-vimUDha.pdf
cp 'mwcolorpages/MW-main (coloured) 953.pdf' pdfpages/mw0953-vizoNita.pdf
cp 'mwcolorpages/MW-main (coloured) 954.pdf' pdfpages/mw0954-vikalpa.pdf
cp 'mwcolorpages/MW-main (coloured) 955.pdf' pdfpages/mw0955-vikRt.pdf
cp 'mwcolorpages/MW-main (coloured) 956.pdf' pdfpages/mw0956-vicakramANa.pdf
cp 'mwcolorpages/MW-main (coloured) 957.pdf' pdfpages/mw0957-vigama.pdf
cp 'mwcolorpages/MW-main (coloured) 958.pdf' pdfpages/mw0958-vighnaka.pdf
cp 'mwcolorpages/MW-main (coloured) 959.pdf' pdfpages/mw0959-vicicit.pdf
cp 'mwcolorpages/MW-main (coloured) 96.pdf' pdfpages/mw0096-alpAmbutIrtha.pdf
cp 'mwcolorpages/MW-main (coloured) 960.pdf' pdfpages/mw0960-vijAvan.pdf
cp 'mwcolorpages/MW-main (coloured) 961.pdf' pdfpages/mw0961-vijRmbhin.pdf
cp 'mwcolorpages/MW-main (coloured) 962.pdf' pdfpages/mw0962-viTThaleza.pdf
cp 'mwcolorpages/MW-main (coloured) 963.pdf' pdfpages/mw0963-vitAna.pdf
cp 'mwcolorpages/MW-main (coloured) 964.pdf' pdfpages/mw0964-vidyAkara.pdf
cp 'mwcolorpages/MW-main (coloured) 965.pdf' pdfpages/mw0965-vitta.pdf
cp 'mwcolorpages/MW-main (coloured) 966.pdf' pdfpages/mw0966-vidUSaNa.pdf
cp 'mwcolorpages/MW-main (coloured) 967.pdf' pdfpages/mw0967-vidyota.pdf
cp 'mwcolorpages/MW-main (coloured) 968.pdf' pdfpages/mw0968-vidhAyaka.pdf
cp 'mwcolorpages/MW-main (coloured) 969.pdf' pdfpages/mw0969-vidhAraya.pdf
cp 'mwcolorpages/MW-main (coloured) 97.pdf' pdfpages/mw0097-avakramaNa.pdf
cp 'mwcolorpages/MW-main (coloured) 970.pdf' pdfpages/mw0970-vinikarttavya.pdf
cp 'mwcolorpages/MW-main (coloured) 971.pdf' pdfpages/mw0971-vinirmA.pdf
cp 'mwcolorpages/MW-main (coloured) 972.pdf' pdfpages/mw0972-vinayana.pdf
cp 'mwcolorpages/MW-main (coloured) 973.pdf' pdfpages/mw0973-viprakanyA.pdf
cp 'mwcolorpages/MW-main (coloured) 974.pdf' pdfpages/mw0974-vipariNata.pdf
cp 'mwcolorpages/MW-main (coloured) 975.pdf' pdfpages/mw0975-vipulaka.pdf
cp 'mwcolorpages/MW-main (coloured) 976.pdf' pdfpages/mw0976-vipralApin.pdf
cp 'mwcolorpages/MW-main (coloured) 977.pdf' pdfpages/mw0977-vibAdha.pdf
cp 'mwcolorpages/MW-main (coloured) 978.pdf' pdfpages/mw0978-vibhASA.pdf
cp 'mwcolorpages/MW-main (coloured) 979.pdf' pdfpages/mw0979-vibhUman.pdf
cp 'mwcolorpages/MW-main (coloured) 98.pdf' pdfpages/mw0098-avaghoSa.pdf
cp 'mwcolorpages/MW-main (coloured) 980.pdf' pdfpages/mw0980-vimalaya.pdf
cp 'mwcolorpages/MW-main (coloured) 981.pdf' pdfpages/mw0981-vimarda.pdf
cp 'mwcolorpages/MW-main (coloured) 982.pdf' pdfpages/mw0982-viraja.pdf
cp 'mwcolorpages/MW-main (coloured) 983.pdf' pdfpages/mw0983-virAja.pdf
cp 'mwcolorpages/MW-main (coloured) 984.pdf' pdfpages/mw0984-virodhaka.pdf
cp 'mwcolorpages/MW-main (coloured) 985.pdf' pdfpages/mw0985-vilabdha.pdf
cp 'mwcolorpages/MW-main (coloured) 986.pdf' pdfpages/mw0986-viluNT.pdf
cp 'mwcolorpages/MW-main (coloured) 987.pdf' pdfpages/mw0987-vivAdin.pdf
cp 'mwcolorpages/MW-main (coloured) 988.pdf' pdfpages/mw0988-vivekin.pdf
cp 'mwcolorpages/MW-main (coloured) 989.pdf' pdfpages/mw0989-vivardhana.pdf
cp 'mwcolorpages/MW-main (coloured) 99.pdf' pdfpages/mw0099-avatRR.pdf
cp 'mwcolorpages/MW-main (coloured) 990.pdf' pdfpages/mw0990-vizalyaya.pdf
cp 'mwcolorpages/MW-main (coloured) 991.pdf' pdfpages/mw0991-vizeSaka.pdf
cp 'mwcolorpages/MW-main (coloured) 992.pdf' pdfpages/mw0992-vizrAnti.pdf
cp 'mwcolorpages/MW-main (coloured) 993.pdf' pdfpages/mw0993-vizvajinva.pdf
cp 'mwcolorpages/MW-main (coloured) 994.pdf' pdfpages/mw0994-vizvavyApti.pdf
cp 'mwcolorpages/MW-main (coloured) 995.pdf' pdfpages/mw0995-vizvAhA.pdf
cp 'mwcolorpages/MW-main (coloured) 996.pdf' pdfpages/mw0996-viSabhujaMga.pdf
cp 'mwcolorpages/MW-main (coloured) 997.pdf' pdfpages/mw0997-viSamaka.pdf
cp 'mwcolorpages/MW-main (coloured) 998.pdf' pdfpages/mw0998-viSudruh.pdf
cp 'mwcolorpages/MW-main (coloured) 999.pdf' pdfpages/mw0999-viSTambhita.pdf
