#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Consume the human votes from the A18 review sheet.

Input:  review/decisions.json (downloaded from A18_sense_verify_sheet.html)
        sense_verify_items.json (the sample the votes refer to)
Output: SENSE_VERIFY_RESULTS.md — per-stratum sense-attestation rates, the
        P3 numbers ("of the band-3 L.-hedged lemmas attested in DCS, X%
        are attested in the hedged SENSE; control ceiling Y%").

Refuses to report if any item is unvoted (decision null) — a partial pass
must not silently masquerade as the result.
"""
import sys, os, json, datetime
sys.stdout.reconfigure(encoding='utf-8')
sys.stderr.reconfigure(encoding='utf-8')

HERE = os.path.dirname(os.path.abspath(__file__))
DEC  = os.path.join(HERE, 'review', 'decisions.json')
if not os.path.exists(DEC):
    sys.exit('review/decisions.json not found — download it from the sheet first.')

dec   = json.load(open(DEC, encoding='utf-8'))
items = {i['k1_slp1']: i for i in
         json.load(open(os.path.join(HERE, 'sense_verify_items.json'), encoding='utf-8'))}

votes = {d['id']: d for d in dec['items']}
unknown = [i for i in votes if i not in items]
if unknown:
    sys.exit(f'decisions.json contains ids not in the sample: {unknown[:5]}')
unvoted = [i for i, d in votes.items() if d['decision'] is None]
if unvoted:
    sys.exit(f'incomplete pass — {len(unvoted)} unvoted items (e.g. {unvoted[:5]}). '
             'Finish the sheet, re-download, retry.')

def tally(stratum):
    t = {'approve': 0, 'reject': 0, 'defer': 0}
    ks = []
    for k, it in items.items():
        if it['stratum'] != stratum: continue
        t[votes[k]['decision']] += 1
        ks.append(k)
    return t, len(ks)

h, nh = tally('hedge')
c, nc = tally('control')
today = datetime.date.today().strftime('%d-%m-%Y')

def pct(a, n): return f'{100*a/n:.1f}%' if n else 'n/a'

notes = [(k, votes[k]['decision'], votes[k]['note'])
         for k in sorted(votes) if votes[k].get('note')]
note_rows = '\n'.join(f'| `{k}` | {d} | {n} |' for k, d, n in notes) or '| — | — | — |'

open(os.path.join(HERE, 'SENSE_VERIFY_RESULTS.md'), 'w', encoding='utf-8').write(f'''# A18 sense-verification results (human band-3 `L.` pass)

_Adjudicated: {today} · sheet `{dec["sheet_id"]}` · decided {dec.get("decided","?")}_

| Stratum | n | sense attested | homograph / other sense | unsure |
|---|--:|--:|--:|--:|
| **L.-hedged (band 3)** | {nh} | {h["approve"]} ({pct(h["approve"], nh)}) | {h["reject"]} ({pct(h["reject"], nh)}) | {h["defer"]} |
| **Control (text-cited)** | {nc} | {c["approve"]} ({pct(c["approve"], nc)}) | {c["reject"]} ({pct(c["reject"], nc)}) | {c["defer"]} |

**P3 reading.** Lemma-level recoverability of the `L.` hedge was ~31%
(lexicographer_dcs). At SENSE level, of the DCS-attested band-3 hedged lemmas,
**{pct(h["approve"], nh)}** are attested in the hedged sense itself
(control ceiling {pct(c["approve"], nc)} — votes below the ceiling indicate
homograph collision or sense drift, the caveat SYNTHESIS.md requires the
claim to carry).

## Verifier notes

| item | decision | note |
|---|---|---|
{note_rows}

_Auto-generated by apply_decisions.py from the human decisions.json._
''')
print(f'hedge: {h} / {nh}   control: {c} / {nc}')
print('wrote SENSE_VERIFY_RESULTS.md')
